### PR TITLE
test: add annotation for WIP test cases

### LINKED ISSUE #3001: feat: UnresolvedBug annotation
The most useful sort of bug report is actually a pull request with a failing test case. We do have quite a lote of those, and that's great.
But, today we cannot merge them as they would break CI. 
What we could do (thanks @oscarlvp ) is having an annotation for test case `@UnresolvedBug`. We would not run these test in CI, but a regular `mvn test` would run them.

WDYT?

### PR DESCRIPTION
**Pull request by MartinWitt**
Fix #3001

added one marker class and annotation for two features.
`@Category(UnresolvedBug.class) `excludes test from CI but not from maven test.
`@GithubIssue(String)` allows linking your issue number with a (failing) testcase.

Added check for every GitHub annotation, that an issue with the number exists and every testcase with an Category Annotation has an Github annotation.
Checking if the issue is open would be possible, but maybe you want to link a closed issue?

For showcasing the new feature i add the testcase from #3281.
If someone likes it, it could be included in the CONTRIBUTING guide.

The new feature needed a json parser. Gson was pretty easy to use, but could be changed if someone wants to include a different one.
Lastly both new files need an exclusion from the SpoonArchitectureEnforcerTest::testGoodTestClassNames because having test in the classnames would harm the readability. 

wdyt?

### CODE REVIEW

**Comment by monperrus** [comment]
Super cool!

What about simplifying and having a single annotation:

```
@Category(UnresolvedBug.class)
@GitHubIssue(issueNumber = "3281")
```

becomes 

```
@UnresolvedBug(issueNumber = "3281")
```
?

**Comment by MartinWitt** [comment]
Would be better, but for ignoring tests in the CI the [junit category](https://junit.org/junit4/javadoc/4.12/org/junit/experimental/categories/Category.html) seems the clean way in junit 4.12.
Not using this annotation could be possible, but would make different testing in CI and local very hacky (see [https://stackoverflow.com/questions/37603075/create-annotation-for-junit-category](url). Upgrading to junit 5 would make it possible [see](https://junit.org/junit5/docs/current/user-guide/#writing-tests-meta-annotations)

**Comment by monperrus** [comment]
We already use junit5 (see pom.xml). One solution may be that we require the annotation to be put on
Junit5 tests only.

**Comment by MartinWitt** [comment]
I sadly wasn't able to filter and run tests via junit5 tags. Maybe someone is more experienced in junit5 and maven surefire.

**Comment by monperrus** [comment]
I see.

Does it work with the category only?

Plus `UnresolvedBug` is both a marker and a test class containing tests, which is confusing. Could we split them in `UnresolvedBug` and `UnresolvedBugTest`?

As a marker, could `UnresolvedBug` be an interface?

**Comment by MartinWitt** [comment]
I wasn't able to get it running using junit5 tags.
Splitting the class in marker interface and test class is a good point.
Added one sentence in the contributing guide for failing test cases.

File: src/test/java/spoon/test/GitHubIssue.java [hunk 1]
```diff
@@ -0,0 +1,18 @@
...
+import java.lang.annotation.ElementType;
+import java.lang.annotation.Retention;
+import java.lang.annotation.RetentionPolicy;
+import java.lang.annotation.Target;
+
+
+@Retention(RetentionPolicy.RUNTIME)
+@Target(ElementType.METHOD)
+public @interface GitHubIssue {
+	String issueNumber();
```
Comment (monperrus) [inline src/test/java/spoon/test/GitHubIssue.java]: what about returning an int instead of a String?

File: src/test/java/spoon/test/architecture/SpoonArchitectureEnforcerTest.java [hunk 2]
```diff
@@ -232,6 +232,9 @@ public void metamodelPackageRule() {
 
 	@Test
 	public void testGoodTestClassNames() {
+		//some testclasses are util only and dont have to follow the naming convention for better readability
+		Set<String> testUtilClasses = new HashSet<>(Arrays.asList("spoon.test.GitHubIssue", "spoon.test.UnresolvedBug"));
```
[the remark this answers is not in the document]
Comment (MartinWitt) [reply src/test/java/spoon/test/architecture/SpoonArchitectureEnforcerTest.java]: 100% correct. Changed it

File: src/test/java/spoon/test/GitHubIssue.java (hunk 1 above)
Comment (MartinWitt) [reply src/test/java/spoon/test/GitHubIssue.java]: Sounds good to me. We can safely assume github issue numbers fit in int.

File: src/test/java/spoon/test/UnresolvedBugTest.java [hunk 3]
```diff
@@ -0,0 +1,74 @@
...
+		testMethods = testMethods.stream()
+				.filter(v -> v.hasAnnotation(Test.class) && v.hasAnnotation(GitHubIssue.class))
+				.collect(Collectors.toList());
+		for (CtMethod<?> ctMethod : testMethods) {
+			int issueNumber = ctMethod.getAnnotation(GitHubIssue.class).issueNumber();
+			URL url = new URL(githubURL + issueNumber);
+			// because readAllBytes is jdk9 only
+			String data = new BufferedReader(new InputStreamReader(url.openStream())).lines().collect(Collectors.joining());
+			JsonObject issue = new Gson().fromJson(data, JsonObject.class);
+			assertTrue(issue.get("number").getAsInt()==issueNumber);
```
Comment (monperrus) [inline src/test/java/spoon/test/UnresolvedBugTest.java]: +check that the issue is still open? (looks straighforward to do)

Comment (MartinWitt) [reply src/test/java/spoon/test/UnresolvedBugTest.java]: added

**Comment by monperrus** [comment]
Thanks a lot @MartinWitt for this cool testing feature!

**Comment by monperrus** [comment]
Master is broken: https://travis-ci.org/INRIA/spoon/jobs/660725438

A flaky test? WDYT?

**Comment by MartinWitt** [comment]
is there some way to get the full error message? Maybe using the github API in a ci wasn't a good idea. Possible fix would be remove the test, because a flaky test is really bad.

**Comment by monperrus** [comment]
Upper in the log:

```
[INFO] Running spoon.test.UnresolvedBugTest
[ERROR] Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 13.449 s <<< FAILURE! - in spoon.test.UnresolvedBugTest
[ERROR] checkGithubIssueAnnotations(spoon.test.UnresolvedBugTest)  Time elapsed: 0.383 s  <<< ERROR!
java.io.IOException: Server returned HTTP response code: 403 for URL: https://api.github.com/repos/INRIA/spoon/issues/3281
	at spoon.test.UnresolvedBugTest.checkGithubIssueAnnotations(UnresolvedBugTest.java:47)
```

**Comment by MartinWitt** [comment]
403 Error means either rate limit or missing user agent. Looking at the other CI tests i would guess rate limit exceeded [see](https://developer.github.com/v3/). For unregistered users 60 API calls per hour per IP. Guessing that we share the CI IP with other users, it's a bad test. 
So either have a oauth token in the CI ( is this possible?), check before the test the rate limit or remove the test?

**Comment by monperrus** [comment]
On master, there is an environment variable GITHUB_AUTH_TOKEN that we can use in the test case.
