### PR TITLE
Fix NPE in anonymous class in noclasspath mode.

### LINKED ISSUE #406: NPE in noclasspath
spoon4.3 -x -i IndexWriter.java (attached
[IndexWriter.java.txt](https://github.com/INRIA/spoon/files/33839/IndexWriter.java.txt)
)

results in 

```
java.lang.NullPointerException
	at spoon.support.compiler.jdt.JDTTreeBuilder.visit(JDTTreeBuilder.java:2255)
	at org.eclipse.jdt.internal.compiler.ast.MessageSend.traverse(MessageSend.java:1008)
	at spoon.support.compiler.jdt.JDTTreeBuilder.buildCommonPartForCtNewClassAndCtConstructorCall(JDTTreeBuilder.java:1636)
	at spoon.support.compiler.jdt.JDTTreeBuilder.visit(JDTTreeBuilder.java:2474)
	at org.eclipse.jdt.internal.compiler.ast.QualifiedAllocationExpression.traverse(QualifiedAllocationExpression.java:587)
	at spoon.support.compiler.jdt.JDTTreeBuilder.visit(JDTTreeBuilder.java:2274)
	at org.eclipse.jdt.internal.compiler.ast.MessageSend.traverse(MessageSend.java:1008)
	at org.eclipse.jdt.internal.compiler.ast.Block.traverse(Block.java:136)
	at org.eclipse.jdt.internal.compiler.ast.SynchronizedStatement.traverse(SynchronizedStatement.java:212)
	at spoon.support.compiler.jdt.JDTTreeBuilder.visit(JDTTreeBuilder.java:1937)
	at org.eclipse.jdt.internal.compiler.ast.ConstructorDeclaration.traverse(ConstructorDeclaration.java:577)
	at spoon.support.compiler.jdt.JDTTreeBuilder.visit(JDTTreeBuilder.java:3024)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.traverse(TypeDeclaration.java:1338)
	at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.traverse(CompilationUnitDeclaration.java:748)
	at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.traverse(CompilationUnitDeclaration.java:709)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildSources(JDTBasedSpoonCompiler.java:247)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:500)
	at fr.inria.sacha.spoon.diffSpoon.DiffSpoon.getCtClass(DiffSpoon.java:108)
	at fr.inria.sacha.spoon.diffSpoon.DiffSpoon.compare(DiffSpoon.java:148)
	at fr.inria.sacha.spoon.diffSpoon.DiffSpoonTest.test_t_224771(DiffSpoonTest.java:706)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)


```

### PR DESCRIPTION
**Pull request by GerardPaligot**
If the PR is ok for everyone, I can squash commits in only one.

Closes #406

### CODE REVIEW

File: src/test/java/spoon/test/TestUtils.java [hunk 1]
```diff
@@ -57,9 +57,18 @@ public static Factory build(Class<?>... classesToBuild) throws Exception {
...
 
 	public static void canBeBuild(File outputDirectoryFile, int complianceLevel) {
+		canBeBuild(outputDirectoryFile, complianceLevel, false);
+	}
+
+	public static void canBeBuild(String outputDirectory, int complianceLevel) {
+		canBeBuild(outputDirectory, complianceLevel, false);
+	}
+
+	public static void canBeBuild(File outputDirectoryFile, int complianceLevel, boolean noClasspath) {
```
Comment (GerardPaligot) [inline src/test/java/spoon/test/TestUtils.java]: `canBeBuild` to `canBeBuilt`

**Comment by GerardPaligot** [comment]
@monperrus PR ok.
