### PR TITLE
fix(getparent): getParent(Filter) does not return the current element when it matches the filter

### LINKED ISSUE #637: getParent(Filter) return this when the element match the filter

### PR DESCRIPTION
**Pull request by tdurieux**
close #637

### CODE REVIEW

File: src/test/java/spoon/test/parent/ParentTest.java [hunk 1]
```diff
@@ -42,6 +33,14 @@
 import spoon.reflect.visitor.filter.TypeFilter;
 import spoon.test.replace.testclasses.Tacos;
 
+import java.util.Stack;
```
Comment (GerardPaligot) [inline src/test/java/spoon/test/parent/ParentTest.java]: Seems unused.
