### PR TITLE
Fix NPE when Spoon launch with a wrong path for input resource

### LINKED ISSUE #1042: NPE when the inputResource is a wrong path
Just created a small test: 
```
        @Test
	public void testFileSpooned() throws Exception {
		final Launcher launcher = new Launcher();
		launcher.getEnvironment().setNoClasspath(true);
		launcher.addInputResource("./src/test/MyWrongJavaFile.java");
		launcher.run();
		assertTrue(launcher.getModel().getRootPackage() != null);
	}
```

Failed in error with a NPE.

### PR DESCRIPTION
**Pull request by surli**
Fix #1042 and now encapsulate a FileNotFoundException inside a SpoonException in case of a wrong path given to Spoon.

### CODE REVIEW

File: src/test/java/spoon/test/api/FileSystemFolderTest.java [hunk 1]
```diff
@@ -19,4 +25,17 @@ public void jarFileIsNotSubfolder() {
...
 		assertTrue(subFolders.isEmpty());
 	}
+
+	@Rule
+	public ExpectedException expectedEx = ExpectedException.none();
+
+	@Test
+	public void testLauncherWithWrongPathAsInput() {
+		expectedEx.expect(SpoonException.class);
+		expectedEx.expectMessage("java.io.FileNotFoundException: The following file does not exist: /Users/urli/Github/spoon/src/wrong/direction/File.java");
```
Comment (retuxx) [inline src/test/java/spoon/test/api/FileSystemFolderTest.java]: Should a test case really depend on the message of an exception?

Comment (surli) [inline src/test/java/spoon/test/api/FileSystemFolderTest.java]: Oh. Indeed I was a bit fast in my cut & paste. The intent was only to paste the FileNotFound. I fix that.

Comment (retuxx) [inline src/test/java/spoon/test/api/FileSystemFolderTest.java]: Furthermore, I'm pretty sure that most of us do not clone Spoon into: `/Users/urli/Github/spoon` :)

File: src/test/java/spoon/test/api/FileSystemFolderTest.java [hunk 2]
```diff
@@ -19,4 +25,17 @@ public void jarFileIsNotSubfolder() {
...
 		assertTrue(subFolders.isEmpty());
 	}
+
+	@Rule
+	public ExpectedException expectedEx = ExpectedException.none();
+
+	@Test
+	public void testLauncherWithWrongPathAsInput() {
+		expectedEx.expect(SpoonException.class);
+		expectedEx.expectMessage("java.io.FileNotFoundException");
```
Comment (surli) [inline src/test/java/spoon/test/api/FileSystemFolderTest.java]: Change to use a try catch and make the assert in catch
