### PR TITLE
fix(RtParameter): fixes #2444

### LINKED ISSUE #2444: SpoonClassNotFoundException: cannot create shadow class (RtParameter with Nested Class with Generics)
While trying to build the model for the following java project:
```sh
git clone https://github.com/killbill/killbill.git
cd killbill
# realease 0.18.21
git reset --hard 382381b
```
With this code:
```java
File pom = new File("/path/to/killbill/pom.xml");
MavenLauncher launcher = new MavenLauncher(
    pom.getParentFile().getAbsolutePath(),
    MavenLauncher.SOURCE_TYPE.APP_SOURCE);
launcher.getEnvironment().setAutoImports(true);
launcher.buildModel();
CtModel model = launcher.getModel();
```
I get the following error trace:

```
spoon.support.SpoonClassNotFoundException: cannot create shadow class: com.google.common.collect.LinkedListMultimap

	at spoon.reflect.factory.TypeFactory.get(TypeFactory.java:543)
	at spoon.support.compiler.jdt.JDTImportBuilder.getOrLoadClass(JDTImportBuilder.java:128)
	at spoon.support.compiler.jdt.JDTImportBuilder.build(JDTImportBuilder.java:83)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildModel(JDTBasedSpoonCompiler.java:488)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildUnitsAndModel(JDTBasedSpoonCompiler.java:382)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildSources(JDTBasedSpoonCompiler.java:331)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:120)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:103)
	at spoon.Launcher.buildModel(Launcher.java:768)
	at se.kth.castor.LibraryTest.testPb(LibraryTest.java:80)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at spoon.support.visitor.java.reflect.RtParameter.getDeclaredAnnotations(RtParameter.java:84)
	at spoon.support.visitor.java.JavaReflectionVisitorImpl.visitParameter(JavaReflectionVisitorImpl.java:388)
	at spoon.support.visitor.java.JavaReflectionTreeBuilder.visitParameter(JavaReflectionTreeBuilder.java:325)
	at spoon.support.visitor.java.JavaReflectionVisitorImpl.visitConstructor(JavaReflectionVisitorImpl.java:322)
	at spoon.support.visitor.java.JavaReflectionTreeBuilder.visitConstructor(JavaReflectionTreeBuilder.java:262)
	at spoon.support.visitor.java.JavaReflectionVisitorImpl.visitClass(JavaReflectionVisitorImpl.java:81)
	at spoon.support.visitor.java.JavaReflectionTreeBuilder.visitClass(JavaReflectionTreeBuilder.java:158)
	at spoon.support.visitor.java.JavaReflectionVisitorImpl.visitType(JavaReflectionVisitorImpl.java:123)
	at spoon.support.visitor.java.JavaReflectionVisitorImpl.visitClass(JavaReflectionVisitorImpl.java:108)
	at spoon.support.visitor.java.JavaReflectionTreeBuilder.visitClass(JavaReflectionTreeBuilder.java:158)
	at spoon.support.visitor.java.JavaReflectionTreeBuilder.scan(JavaReflectionTreeBuilder.java:115)
	at spoon.reflect.factory.TypeFactory.get(TypeFactory.java:541)
```
I suspect that there is a missmatch between `constructor.getParameterAnnotations()` actual length (called later) and the index declared in `RtParameter#parametersOf(Constructor)` [line 180 of spoon/src/main/java/spoon/support/visitor/java/reflect/RtParameter.java](https://github.com/INRIA/spoon/blob/master/src/main/java/spoon/support/visitor/java/reflect/RtParameter.java#L180)

The offending decompiled bytecode is the following
```java
public class LinkedListMultimap<K, V> implements ListMultimap<K, V>, Serializable {
...
private class ValueForKeyIterator implements ListIterator<V> {
        final Object key;
        int nextIndex;
        LinkedListMultimap.Node<K, V> next;
        LinkedListMultimap.Node<K, V> current;
        LinkedListMultimap.Node<K, V> previous;

        ValueForKeyIterator(@Nullable Object key) {
            this.key = key;
            this.next = (LinkedListMultimap.Node)LinkedListMultimap.this.keyToKeyHead.get(key);
        }

        public ValueForKeyIterator(@Nullable Object key, int index) {
            int size = LinkedListMultimap.this.keyCount.count(key);
            Preconditions.checkPositionIndex(index, size);
            if (index >= size / 2) {
                this.previous = (LinkedListMultimap.Node)LinkedListMultimap.this.keyToKeyTail.get(key);
                this.nextIndex = size;

                while(index++ < size) {
                    this.previous();
                }
            } else {
                this.next = (LinkedListMultimap.Node)LinkedListMultimap.this.keyToKeyHead.get(key);

                while(index-- > 0) {
                    this.next();
                }
            }

            this.key = key;
            this.current = null;
        }
 ...
}
...
}
```

I am investigating, but any help or advice is more than welcome!

### PR DESCRIPTION
**Pull request by nharrand**
This PR aims at fixing #2444 by handling differences in size between `java.lang.reflect.Executable#getParameterAnnotations()`, `java.lang.reflect.Constructor#getParameterTypes()`and `java.lang.reflect.Constructor#getGenericParameterTypes()` despite inconsistencies between javac and eclipse.

### CODE REVIEW

**Comment by nharrand** [comment]
This code is ready for review!

File: src/main/java/spoon/support/visitor/java/reflect/RtParameter.java [hunk 1]
```diff
@@ -81,7 +81,18 @@ public Type getGenericType() {
 	 */
 	public Annotation[] getDeclaredAnnotations() {
 		if (method == null) {
-			return constructor.getParameterAnnotations()[index];
+			/*
+			 * According to oracle sources (for jdk 8) for java.lang.reflect.Executable#getParameterAnnotations(),
+			 * the length of the returned array may vary at the discretion of the compiler.
+			 * It seems that eclipse and javac do not produce the same results.
```
Comment (monperrus) [inline src/main/java/spoon/support/visitor/java/reflect/RtParameter.java]: "eclipse and javac do not produce the same results": WTF!!

**Comment by monperrus** [comment]
Thanks!
