### PR TITLE
fix: inner types without file should not crash Environment#report

### LINKED ISSUE #4997: [Bug]: Environment.report(...) throws NullPointerException
### Describe the bug

using getEnvironment.report(processor, Level.INFO, element, "Message...") in my processor i get a NullPointerException if the element is implicit.

### Source code you are trying to analyze/transform

```Java
package fr.inria.gforge.spoon.analysis;

/**
 * The Class Testcase2.
 *
 * testcase to show NullPointerException
 */
public class Testcase2
{

    private class A
    {

    }

    private class B extends A
    {

        /**
         * Instantiates a new b.
         */
        public B()
        {
            super();
        }
    }

    public static void main(String[] args)
    {
        Testcase2 t = new Testcase2();
        t.test();
    }

    public String test()
    {
        var b = new B();
        return b.toString();
    }
}
```

### Source code for your Spoon processing

```Java
package fr.inria.gforge.spoon.analysis;

import java.util.List;

import spoon.processing.AbstractProcessor;
import spoon.reflect.code.CtInvocation;
import spoon.reflect.declaration.CtConstructor;
import spoon.reflect.visitor.Query;
import spoon.reflect.visitor.filter.TypeFilter;
import spoon.support.Level;

/**
 * Processor to show {@link NullPointerException} thrown if element is implicit.
 *
 * @author r.b.
 *
 */
public class BugProcessor extends AbstractProcessor<CtConstructor<?>>
{

    /**
     * implementation walks through all invocations and just prints them
     *
     * @see spoon.processing.AbstractProcessor#isToBeProcessed(spoon.reflect.declaration.CtElement)
     *
     * @param candidate element to check
     * @return true if the element should be processed
     */
    public boolean isToBeProcessed(CtConstructor<?> candidate)
    {

        boolean process = false;
        List<CtInvocation<?>> invocations = Query.getElements(candidate, new TypeFilter<>(CtInvocation.class));

        invocations.forEach(i -> getEnvironment().report(this, Level.INFO, i, "Message"));

        return process;
    }

    /**
     * @see spoon.processing.Processor#process(spoon.reflect.declaration.CtElement)
     *
     * @param element
     */
    @Override
    public void process(CtConstructor<?> element)
    {
        // no functionality here ...
    }
}
```

### Actual output

```Java
Caused by: java.lang.NullPointerException
    at spoon.support.StandardEnvironment.report (StandardEnvironment.java:265)
    at fr.inria.gforge.spoon.analysis.BugProcessor.lambda$isToBeProcessed$0 (BugProcessor.java:57)
    at java.util.ArrayList.forEach (ArrayList.java:1541)
    at fr.inria.gforge.spoon.analysis.BugProcessor.isToBeProcessed (BugProcessor.java:57)
    at fr.inria.gforge.spoon.analysis.BugProcessor.isToBeProcessed (BugProcessor.java:40)
    at spoon.support.visitor.ProcessingVisitor.scan (ProcessingVisitor.java:71)
```

### Expected output

```Java
No Exception
```

### Spoon Version

10.2.0

### JVM Version

11

### What operating system are you using?

win10

### PR DESCRIPTION
**Pull request by MartinWitt**
fixes #4997

### CODE REVIEW

File: src/main/java/spoon/support/StandardEnvironment.java [hunk 1]
```diff
@@ -256,13 +256,20 @@ public void report(Processor<?> processor, Level level, CtElement element, Strin
 		if (sp == null) {
 			buffer.append(" (Unknown Source)");
 		} else {
-			// TODO: will explode if type == null
-			buffer.append(" at " + type.getQualifiedName() + ".");
+			if (type != null) {
+				buffer.append(" at " + type.getQualifiedName() + ".");
```
Comment (I-Al-Istannen) [inline src/main/java/spoon/support/StandardEnvironment.java:260]:
```suggestion
				buffer.append(" at ").append(type.getQualifiedName()).append(".");
```
If you already have a buffer I'd use its `append` method instead of string concatenation inside the argument.

File: src/main/java/spoon/support/StandardEnvironment.java [hunk 2]
```diff
@@ -256,13 +256,20 @@ public void report(Processor<?> processor, Level level, CtElement element, Strin
...
+			} else {
+				buffer.append("at  (??).");
+			}
 			CtExecutable<?> exe = (element instanceof CtExecutable) ? (CtExecutable<?>) element : element.getParent(CtExecutable.class);
 			if (exe != null) {
 				buffer.append(exe.getSimpleName());
 			}
-			buffer.append("(" + sp.getFile().getName() + ":" + sp.getLine() + ")");
+			if (sp.getFile() != null) {
+				buffer.append("(" + sp.getFile().getName() + ":" + sp.getLine() + ")");
```
Comment (I-Al-Istannen) [inline src/main/java/spoon/support/StandardEnvironment.java:269]:
```suggestion
				buffer.append("(").append(sp.getFile().getName()=.append(":").append(sp.getLine()).append(")");
```

**Review by I-Al-Istannen — CHANGES_REQUESTED** [review]
Just some preliminar

**Review by I-Al-Istannen — CHANGES_REQUESTED** [review]
LGTM, just a small formatting issue

File: src/test/java/spoon/test/logging/LogTest.java [hunk 3]
```diff
@@ -103,4 +111,22 @@ public void testLoggingOff() {
...
+			public void process(CtConstructor<?> element) {
+				// do nothing
+			}
+			public boolean isToBeProcessed(CtConstructor<?> candidate) {
+        List<CtInvocation<?>> invocations = Query.getElements(candidate, new TypeFilter<>(CtInvocation.class));
+        invocations.forEach(i -> getEnvironment().report(this, Level.INFO, i, "Message"));
+        return false;
+			}
+		};
+		assertDoesNotThrow(() ->new FluentLauncher().inputResource(codePath).processor(processor).buildModel());
```
[the remark this answers is not in the document]
Comment (MartinWitt) [reply src/test/java/spoon/test/logging/LogTest.java]: Another git fail on my side to add to the endless list of git fails. I failed to push the new formatting and was a bit confused with the review inside my IDE. The formatting should be fine now.

**Review by I-Al-Istannen — APPROVED** [review]
