### PR TITLE
review: Add mechanism to sort compilation units

### LINKED ISSUE #1929: discussion: buildModel and CompilationUnits order
While working on #1928 I get stuck on a bug which was appearing when building the model from the input path `./src/test/java/spoon/test/` and disappearing when building the model from path: `./src/test/java/spoon/test/annotation/testclasses/shadow`. 
And my entire test was built only with types coming from `./src/test/java/spoon/test/annotation/testclasses/shadow`.
The bug was in fact coming because one type was resolving **before** another one I needed in the first case, and **after** it in the second case. 

So in other word, I got a bug because of the order of resolution of the compilation units. The interesting point is that I was quite confident on my implementation, until my test crashes because I changed the path and so changed the order of resolution. 

What action should we take about this? 

1. None 
2. To fix the order in which compilation units are sorted in JDTBasedSpoonCompiler and to rely only on this order
3. To define a random order with a seed, and to check in CI tests with different seeds, to ensure everything's passing even if the classes are not resolved in the same order

WDYT?

### PR DESCRIPTION
**Pull request by surli**
This PR should fix #1929

### CODE REVIEW

File: src/main/java/spoon/support/compiler/jdt/CompilationUnitComparator.java [hunk 1]
```diff
@@ -0,0 +1,49 @@
...
+
+import java.util.Comparator;
+import java.util.Random;
+
+public class CompilationUnitComparator implements Comparator<CompilationUnitDeclaration> {
+
+	@Override
+	public int compare(CompilationUnitDeclaration o1, CompilationUnitDeclaration o2) {
+		int seed = 0;
+		if (System.getenv("SPOON_SEED_CU_COMPARATOR") != null) {
```
Comment (pvojtechovsky) [inline src/main/java/spoon/support/compiler/jdt/CompilationUnitComparator.java]: > copied from javadoc of System#getenv
> If a security manager exists, its checkPermission method is called with a RuntimePermission("getenv."+name) permission. This may result in a SecurityException being thrown. 

It would be cleaner to try catch security exception here.

File: src/main/java/spoon/support/compiler/jdt/JDTBasedSpoonCompiler.java [hunk 2]
```diff
@@ -430,8 +430,11 @@ protected boolean buildUnitsAndModel(JDTBuilder jdtBuilder, SpoonFolder sourcesF
 
 	protected void buildModel(CompilationUnitDeclaration[] units) {
 		JDTTreeBuilder builder = new JDTTreeBuilder(factory);
+		List<CompilationUnitDeclaration> unitList = Arrays.asList(units);
+		unitList.sort(new CompilationUnitComparator());
```
Comment (pvojtechovsky) [inline src/main/java/spoon/support/compiler/jdt/JDTBasedSpoonCompiler.java]: Is it intentional that this sort sorts the origin `units` array? It actually modifies the array sent from outside. I have checked who actually calls it and it looks like it is actually no problem, but it would be safer to sort a copy of that array.
WDYT?

Comment (surli) [reply src/main/java/spoon/support/compiler/jdt/JDTBasedSpoonCompiler.java]: You're right: I wasn't aware that `Arrays.asList` was keeping up the link with the original array. Good thing to know 👍

**Comment by pvojtechovsky** [comment]
Java code is OK for me.
@monperrus please check the CI stuff ... I do not know that.

**Comment by monperrus** [comment]
Interesting.

Two comments:

- AFIAU, we do fixed order by default, I thought you wanted to do random order by default.
- I propose to put the variation point outside the comparator, ie having a `RandomizeCompilationUnitOrderComparator` and `FixedOrderBasedOnFileNameCompilationUnitComparator`

**Comment by surli** [comment]
> we do fixed order by default, I thought you wanted to do random order by default.

No as I said in #1929 that we should have always the same order but we should test that we are not dependent of the order: a way to do that is to randomize the order when testing. 

> I propose to put the variation point outside the comparator

OK with that change, I'll do it

**Comment by surli** [comment]
> I propose to put the variation point outside the comparator

Before I do the change, just to be clear, you want me to integrate my test with `getenv` inside `JDTBasedSpoonCompiler` then? It looks a bit ugly...

**Comment by monperrus** [comment]
Yes. We can add a method `JDTBasedSpoonCompiler#orderCompilationUnits` to make it less ugly.

It seems to me that adding a new Travis job for such a specific need and rare bug is somehow overkill, because it is run on all PRs. You suggested a Jenkins job which I tend to prefer. WDYT?

**Comment by surli** [comment]
> We can add a method

OK I'll do it that way

> You suggested a Jenkins job which I tend to prefer. WDYT?

Jenkins does not provide an immediate feedback, however I agree it's overkill to run this test on all PRs commits: a middle way might be to put it only for commits on master.

**Comment by monperrus** [comment]
then we can have a Gakoci job for master.

**Comment by monperrus** [comment]
what about adding a test case?

File: src/test/java/spoon/test/architecture/SpoonArchitectureEnforcerTest.java [hunk 3]
```diff
@@ -328,6 +328,7 @@ public void testSpecPackage() throws Exception {
 		officialPackages.add("spoon.reflect.visitor");
 		officialPackages.add("spoon.reflect");
 		officialPackages.add("spoon.support.comparator");
+		officialPackages.add("spoon.support.comparator.cu");
```
Comment (monperrus) [inline src/test/java/spoon/test/architecture/SpoonArchitectureEnforcerTest.java]: seems overkill to add a new package for those two small classes? spoon.support.comparator would be enough?

**Comment by surli** [comment]
@monperrus it's ready for me.

**Comment by monperrus** [comment]
thanks!
