### PR TITLE
fix(noclasspath): Computes char value of literals in noclasspath.

### LINKED ISSUE #427: NPE in noclasspath
`spoon4.4 -x -i SecondaryIndexManager.java` (file attached)
 gives a NPE

[SecondaryIndexManager.java.txt](https://github.com/INRIA/spoon/files/48626/SecondaryIndexManager.java.txt)

### PR DESCRIPTION
**Pull request by GerardPaligot**
Closes #427

### CODE REVIEW

File: src/main/java/spoon/support/compiler/jdt/JDTTreeBuilder.java [hunk 1]
```diff
@@ -1946,7 +1946,12 @@ public boolean visit(CastExpression castExpression, BlockScope scope) {
 	@Override
 	public boolean visit(CharLiteral charLiteral, BlockScope scope) {
 		CtLiteral<Character> l = factory.Core().createLiteral();
-		l.setValue(charLiteral.constant.charValue());
+		if (charLiteral.constant != null) {
+			l.setValue(charLiteral.constant.charValue());
+		} else {
```
Comment (GerardPaligot) [inline src/main/java/spoon/support/compiler/jdt/JDTTreeBuilder.java]: add comment noclasspath mode.
