### PR TITLE
fix(noclasspath): Builds reference of a parameter in a lambda.

### LINKED ISSUE #779: NPE when calling CtParameter.getReference if parameter is in lambda
Tested Code Fragment:
```java
	public void setStarRatings(HashMap<ViolationType, Integer> userRatings) {
		System.out.println(userRatings);
		userRatings.entrySet().forEach(
				entryPair -> typeRatingFilters.get(entryPair.getKey()).setCurrentNumberOfStars(entryPair.getValue()));
	}
```

Stacktrace:
```java
java.lang.NullPointerException
	at spoon.reflect.factory.ExecutableFactory.createReference(ExecutableFactory.java:102)
	at spoon.reflect.factory.ExecutableFactory.createParameterReference(ExecutableFactory.java:88)
	at spoon.support.reflect.declaration.CtParameterImpl.getReference(CtParameterImpl.java:64)
	at spoon.support.reflect.declaration.CtParameterImpl.getReference(CtParameterImpl.java:39)
```

File from opensource (MIT licenced) project: attachment
[code.zip](https://github.com/INRIA/spoon/files/408677/code.zip)
z

### PR DESCRIPTION
**Pull request by GerardPaligot**
Closes #779

### CODE REVIEW

File: src/test/java/spoon/test/parameters/ParameterTest.java [hunk 1]
```diff
@@ -26,4 +28,21 @@ public void testParameterInNoClasspath() throws Exception {
...
+		launcher.buildModel();
+
+		CtMethod<?> ctMethod = launcher.getFactory().Type().get("Tacos").getMethodsByName("setStarRatings").get(0);
+		CtParameter ctParameter = ctMethod.getBody().getStatement(0).getElements(new TypeFilter<CtParameter>(CtParameter.class) {
+			@Override
+			public boolean matches(CtParameter element) {
+				return "entryPair".equals(element.getSimpleName()) && super.matches(element);
+			}
+		}).get(0);
+		assertNotNull(ctParameter.getReference());
```
Comment (monperrus) [inline src/test/java/spoon/test/parameters/ParameterTest.java]: add assert on lambdaparameterreference.getDeclaration is correct.

Comment (GerardPaligot) [inline src/test/java/spoon/test/parameters/ParameterTest.java]: Done
