### PR TITLE
review: fix: Refactor code to fix runtime exception caused by package name with CtType.INNERTTYPE_SEPARATOR

### LINKED ISSUE #5140: [Bug]: Parsing vallid java files with package name containing $ symbol throws "Invalid package name" exception
### Describe the bug

While trying to parse a file having a package name containing $, the code throws an exception

"Invalid package name com.xxx.public$"

This is due to INNERTYPE_SEPARATOR being set as $ in CtType<T> interface. As this cannot be changed there is no way to parse a file with $ in the package name and the program crashes with the above mentioned exception.

Note package names with $ symbol are valid in java and I do not have control over the source files I am trying to parse. Is there any workaround to parse these files?

### Source code you are trying to analyze/transform

_No response_

### Source code for your Spoon processing

_No response_

### Actual output

_No response_

### Expected output

_No response_

### Spoon Version

10.3.0

### JVM Version

17

### What operating system are you using?

Windows

### PR DESCRIPTION
**Pull request by MartinWitt**
The check is 17 years old and $ is allowed in packages. Interesting that we had no bug reports earlier.

The check for the `CtType.INNERTTYPE_SEPARATOR` that caused runtime exceptions has been removed so that valid packages with `CtType.INNERTTYPE_SEPARATOR` can be found.

A new test has been added to verify that a package with a name containing a dollar sign can be successfully retrieved using the `PackageFactory`.

Fixes #5140

### CODE REVIEW

File: src/test/java/spoon/reflect/factory/PackageFactoryTest.java [hunk 1]
```diff
@@ -29,4 +31,21 @@ void getOrCreate_returnsNestedPackageStructure_whenQualifiedNameRepeatsSimpleNam
 		assertThat(topLevelPackage.getPackage(topLevelPackageName), sameInstance(packageWithDuplicatedSimpleNames));
 		assertThat(packageWithDuplicatedSimpleNames.getParent(), sameInstance(topLevelPackage));
 	}
+	
+		@Test
+		@GitHubIssue(issueNumber = 5140, fixed = true)
+    void testGetPackageWithNameContainingDollarSign() {
+			// contract: A package with a name containing a dollar sign can be retrieved using the PackageFactory
```
Comment (I-Al-Istannen) [inline src/test/java/spoon/reflect/factory/PackageFactoryTest.java:38]: The formatting of this whole file is a bit broken

**Review by I-Al-Istannen — CHANGES_REQUESTED** [review]

File: src/test/java/spoon/reflect/factory/PackageFactoryTest.java (hunk 1 above)
Comment (MartinWitt) [reply src/test/java/spoon/reflect/factory/PackageFactoryTest.java]: There was some random mix between spaces and tabs. It should be fixed now.

**Review by I-Al-Istannen — APPROVED** [review]

**Comment by I-Al-Istannen** [comment]
Thanks :)
