### PR TITLE
review: fix: Correctly adapt type parameters inherited from enclosing classes

### LINKED ISSUE #5226: [Bug]: Generic methods using `isoverride` method will throw an exception
### Describe the bug

Generic methods that use the isOverriding method throw exceptions

```
spoon.SpoonException: Cannot resolve type erasure of the type parameter reference, which is not able to found it's declaration.
	at spoon.support.reflect.reference.CtTypeParameterReferenceImpl.getTypeErasure(CtTypeParameterReferenceImpl.java:176)
	at spoon.support.adaption.TypeAdaptor.isOverriding(TypeAdaptor.java:418)
	at spoon.support.reflect.declaration.CtMethodImpl.isOverriding(CtMethodImpl.java:191)
	at com.huawei.tenet.console.SpoonCommandTest.test(SpoonCommandTest.java:75)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
```

### Source code you are trying to analyze/transform

p12.test1
```Java
package p12;

public class test1 {
    public static class Enclosing<T> {
        public class Enclosed<S> {
            public class ReallyDeepNow<R> {
                void someMethod(S s, T t, R r) {
                }
            }
        }
    }
}
```

p12.test2
```
package p12;

public class test2 {
    public static class ExtendsEnclosing extends test1.Enclosing<String> {
        public class ExtendsEnclosed extends Enclosed<Integer> {
            public class ExtendsReallyDeepNow extends ReallyDeepNow<Long> {
                @Override
                void someMethod(Integer s, String t, Long r) {
                    throw new UnsupportedOperationException();
                }
            }
        }
    }
}
```

### Source code for your Spoon processing

```Java
Launcher launcher = new Launcher();
launcher.getEnvironment().setComplianceLevel(11);
launcher.addInputResource("D:\\IdeaDirectory\\javademo4\\test1\\src\\main\\java\\p12");
CtModel model = launcher.buildModel();
List<CtMethod> elements = model.getElements(new TypeFilter<>(CtMethod.class));
CtMethod test2Method = elements.stream()
.filter(ctMethod -> ctMethod.getPath().toString()
.equals(          "#subPackage[name=p12]#containedType[name=test2]#nestedType[name=ExtendsEnclosing]#nestedType[name=ExtendsEnclosed]#nestedType[name=ExtendsReallyDeepNow]#method[signature=someMethod(java.lang.Integer,java.lang.String,java.lang.Long)]")).collect(Collectors.toList()).get(0);
CtMethod test1Method = elements.stream().filter(ctMethod -> ctMethod.getPath().toString().equals(            "#subPackage[name=p12]#containedType[name=test1]#nestedType[name=Enclosing]#nestedType[name=Enclosed]#nestedType[name=ReallyDeepNow]#method[signature=someMethod(java.lang.Object,java.lang.Object,java.lang.Object)]")).collect(Collectors.toList()).get(0);

if(test2Method.isOverriding(test1Method)){// throw SpoonException
   System.out.println("is overriding");
}
```

### Actual output

```Java
spoon.SpoonException: Cannot resolve type erasure of the type parameter reference, which is not able to found it's declaration.
```

### Expected output

```Java
is overriding
```

### Spoon Version

10.3.0

### JVM Version

11

### What operating system are you using?

window

### PR DESCRIPTION
**Pull request by I-Al-Istannen**
## description
Type adaption did not handle using generics inherited from enclosing classes. In these cases, a type hierarchy from the innermost class to its parent class was built, causing the generic resolution to fail.

This PR fixes this by adjusting building a hierarchy between the *declaring* types instead.

## todo
- [x] Implement the fix
- [x] Document the changes in `docs/type_adaption.md`
- [x] Maybe remove the code duplication in the type adaptor for resolving formal type declarers 

## closes
This closes #5226.

### CODE REVIEW

File: src/main/java/spoon/support/adaption/TypeAdaptor.java [hunk 1]
```diff
@@ -564,6 +564,11 @@
 		CtType<?> endType = findDeclaringType(end);
 		Map<CtTypeReference<?>, DeclarationNode> declarationNodes = new HashMap<>();
 
+		if (needToMoveStartTypeToEnclosingClass(end, endType)) {
```
[the remark this answers is not in the document]
Comment (I-Al-Istannen) [reply src/main/java/spoon/support/adaption/TypeAdaptor.java:568]: @sonatype-lift ignore

File: doc/type_adaption.md [hunk 2]
```diff
@@ -116,6 +116,43 @@ we need to go from any other node in the tree.
...
 If we can not find any hierarchy we currently return the input type unchanged.
 
+#### Adapting generics of enclosing classes
+Java allows classes to use generics of their enclosing class, e.g.
+```java
+public class Outer<A> {
+  public static class Inner<B> {
+    public void bar(A a, B b) {}
+  }
+}
```
Comment (SirYwell) [inline doc/type_adaption.md:126]: This doesn't compile for me, I assume the inner class shouldn't be static?

File: src/test/java/spoon/support/TypeAdaptorTest.java [hunk 3]
```diff
@@ -440,4 +443,53 @@ public <T extends CharSequence> void overloaded(T t) {}
...
+		CtMethod<?> test2Method = methods.stream()
+				.filter(it -> it.getDeclaringType().getSimpleName().startsWith("Extends"))
+				.findAny()
+				.orElseThrow();
+
+		assertTrue(test2Method.isOverriding(test1Method));
+		assertFalse(test1Method.isOverriding(test2Method));
+	}
+
+	public static class UseGenericFromEnclosingType {
```
Comment (SirYwell) [inline src/test/java/spoon/support/TypeAdaptorTest.java:473]: Do we want the classes here or in the resource folder?

**Review by SirYwell — CHANGES_REQUESTED** [review]

File: doc/type_adaption.md (hunk 2 above)
Comment (I-Al-Istannen) [reply doc/type_adaption.md]: Whoops, you are right.

File: src/test/java/spoon/support/TypeAdaptorTest.java (hunk 3 above)
Comment (I-Al-Istannen) [reply src/test/java/spoon/support/TypeAdaptorTest.java:473]: The other tests are also in this file, so I kept those close-by as well.

**Comment by monperrus** [comment]
thanks @I-Al-Istannen
