### PR TITLE
fix: shorter this access

### LINKED ISSUE #826: DefaultJavaPrettyPrinter.visitCtThisAccess
I think it shouldn't rely on getTarget().isImplicit() when printing this qualifier, because classes could be moved around, and Implicit flag is usually not modified.

Such implementation work better for me, probably it should be adapted for DefaultJavaPrettyPrinter itself (+ corner cases, which I omitted in my code because not the case for me):

``` java
    class MyPrinter extends DefaultJavaPrettyPrinter {

        Deque<CtClass<?>> currentThis = new ArrayDeque<>();

        public MyPrinter(Environment env) {
            super(env);
        }

        @Override
        public <T> void visitCtClass(CtClass<T> ctClass) {
            currentThis.push(ctClass);
            super.visitCtClass(ctClass);
            currentThis.pop();
        }

        @Override
        public <T> void visitCtThisAccess(CtThisAccess<T> thisAccess) {
            enterCtExpression(thisAccess);
            if (!thisAccess.isImplicit()) {
                if (thisAccess.getType().getDeclaration() != currentThis.peek()) {
                    visitCtTypeReferenceWithoutGenerics(thisAccess.getType());
                    write(".");
                }
                write("this");
            }
            exitCtExpression(thisAccess);
        }
    }
```

### PR DESCRIPTION
**Pull request by monperrus**
This is an important change in the way we print this access.

The current strategy of writing qualified this `v.l.pack.n.Foo.this.bar()` yields unreadable code even in readable with-imports mode.

This PR fixes this.

In the mid-term, I would like to completely get rid of checks on isImplicit for this accesses, but this requires some additional work on the model. As discussed recently, there are incorrect implicit targets, which nobody detects and reports because they are not printed. Only advanced transformers suffer from them.

The pretty-printing of this accesses was incredibly strongly specified (kudos to @GerardPaligot ), hence the number of changed tests, please review carefully.

closes #826

### CODE REVIEW

File: src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java [hunk 1]
```diff
@@ -719,45 +716,50 @@ public void visitCtDo(CtDo doLoop) {
...
-			if (!(parent instanceof CtFieldWrite) || !thisAccess.equals(((CtFieldWrite) parent).getTarget()) || thisAccess.getParent(CtConstructor.class) == null) {
-				return false;
+			// TODO find a way to remove this check
+			// ideally we sould not rely on implicitness
+			// for correct pretty-printing, because this is fragile
+			// wrt to bugs in the model and when refactoring
+			if (thisTarget.isImplicit()) {
+				// write nothing, "this" is implicit and we unfortunately cannot always know
+				// what the good target is in JDTTreeBuilder
+				return;
```
Comment (monperrus) [inline src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java]: no because the caller checks for implicitness as well (see ctVisitInvocation for instance).

however, this is an interesting question: who is responsible for printing the "."? probably the parent element, as done today (but consistently?).

however instead of 
```
if (target.isImplicit()) {
  scan(target);
  print(".")
}
```
I would prefer 
```
scan(target);
if (somethingHasBeenWritten()) {
  print(".")
}
```
This would be less fragile.

(outside the scope of this PR but I'd like to have your opinion on this)
```

**Comment by monperrus** [comment]
well done. then a test is missing, I'll add it.

**Comment by monperrus** [comment]
simple this compute getTarget() on the fly

File: src/test/java/spoon/test/prettyprinter/QualifiedThisRefTest.java [hunk 2]
```diff
@@ -55,7 +56,8 @@ public void testQualifiedThisRef() {
 		ctTypes.add(ctClass);
 		printer.getElementPrinterHelper().writeHeader(ctTypes, imports);
 		printer.scan(ctClass);
-		assertTrue(printer.getResult().contains("Object o = QualifiedThisRef.Sub.this"));
+		Assert.assertTrue(printer.getResult().contains("Object o = this"));
+		Assert.assertTrue(printer.getResult().contains("Object o = QualifiedThisRef.this"));
```
Comment (tdurieux) [inline src/test/java/spoon/test/prettyprinter/QualifiedThisRefTest.java]: contains is weak...

**Comment by pvojtechovsky** [comment]
I tried the code of this PR with my project and printed version compiles well. I also do not see problem in code ... but there are part which I do not understand, or I am lazy to understand ... :-)

File: src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java [hunk 3]
```diff
@@ -682,8 +681,9 @@ public void visitCtDo(CtDo doLoop) {
 			}
 			if (f.getTarget() != null) {
 				if (!isInitializeStaticFinalField(f.getTarget())) {
+					printer.snapshotLength();
 					scan(f.getTarget());
-					if (!f.getTarget().isImplicit()) {
+					if (printer.hasNewContent()) {
```
Comment (monperrus) [inline src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java]: you're right, replaced by a queue.

Comment (pvojtechovsky) [inline src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java]: what about this code?
```java
printer.getSnapshotLength();
{
...some complex code with many ifs, loops 
... and evil
          return;
... added by somebody else after some years, will bring him hot time ...
}
if (printer.hasNewContent()) {...}
```
this 
```java
int snapshot = printer.getSnapshotLength()
...
if(print.hasNewContent(snapshot)) {...}
```
is little bit more code, but is really safe

Comment (monperrus) [inline src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java]: yes, but looks less elegant. let's wait for the devil to make ugly things :-).

**Comment by monperrus** [comment]
I wanted to go first for shorter and more explicit this accesses. I only keep shorter for now because I don't want to break too much test cases from client code.

For handling explicitness during refactoring, we have to remove implicit in the appropriate setters and refactoring methods.

File: src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java (hunk 3 above)
Comment (pvojtechovsky) [inline src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java]: ;-))

**Comment by monperrus** [comment]
@tdurieux you can merge
