### PR TITLE
review: fix: Subtyping relationships for arrays

### LINKED ISSUE #5462: [Bug]: `ctArrayTypeReference.isSubtypeOf(...)` returns `true` if the array type is a subtype
### Describe the bug

Obviously `Integer[]` is not a `Number`.

### Source code you are trying to analyze/transform

```Java
public class Test { Integer[] field; }
```

### Source code for your Spoon processing

```Java
import org.junit.jupiter.api.Test;
import spoon.Launcher;
import spoon.reflect.declaration.CtClass;
import spoon.reflect.declaration.CtField;
import spoon.reflect.declaration.CtType;
import spoon.reflect.reference.CtArrayTypeReference;
import spoon.reflect.reference.CtTypeReference;

import static org.junit.jupiter.api.Assertions.*;

class TestSpoon {
    @Test
    void testArraySubtype() {
        CtField<?> ctField = Launcher.parseClass("public class Test { Integer[] field; }")
            .getField("field");

        CtTypeReference<?> ctArrayType = ctField.getType();

        assertTrue(ctArrayType instanceof CtArrayTypeReference<?>, "ctArrayType should be an instance of CtArrayTypeReference");
        assertFalse(
            ctArrayType.isSubtypeOf(ctField.getFactory().Type().get(java.lang.Number.class).getReference()),
            "an array of integers should not be a subtype of Number"
        );
    }
}
```

### Actual output

```Java
org.opentest4j.AssertionFailedError: an array of integers should not be a subtype of Number ==> 
Expected :false
Actual   :true
```

### Expected output

_No response_

### Spoon Version

10.4.1-SNAPSHOT

### JVM Version

openjdk version "17.0.1" 2021-10-19 OpenJDK Runtime Environment Temurin-17.0.1+12 (build 17.0.1+12) OpenJDK 64-Bit Server VM Temurin-17.0.1+12 (build 17.0.1+12, mixed mode, sharing)

### What operating system are you using?

Windows 10

### PR DESCRIPTION
**Pull request by I-Al-Istannen**
This one was a bit of a doozy.

Array subtyping needs to be special cased, as Spoon is not able to build a `CtType` for source-level arrays. Similarly, once we are given a shadow `CtType` that refers to an array type, we need to unpack to find the real type to build our hierarchy for. We can not just fall back to the java `Class#isAssignableFrom`, as the super type reference might not be shadowable.

Closes #5462.

### CODE REVIEW

File: src/main/java/spoon/support/adaption/TypeAdaptor.java [hunk 1]
```diff
@@ -150,11 +195,51 @@ public static boolean isSubtype(CtType<?> base, CtTypeReference<?> superRef) {
...
 		}
+
+		// Handle shadow array types, as we can build a CtType for any Class, which includes arrays. We need to lower
+		// them to their innermost component type and then decide subtyping based on their relationship.
+		if (base.isArray() && superRef instanceof CtArrayTypeReference<?>) {
+			if (!base.isShadow()) {
+				throw new SpoonException("There are no source level array type declarations");
+			}
+			Class<?> actualClass = base.getActualClass();
+			// Arrays of different shapes are not subtypes
```
Comment (intrigus-lgtm) [inline src/main/java/spoon/support/adaption/TypeAdaptor.java:206]: This isn't true?
> new Object[0][0] instanceof Object[]
$3 ==> true

This is a consequence of 
- If S and T are both reference types, then S[] >1 T[] iff S >1 T.
- Object >1 Object[]

unless I'm missing some context here.

Comment (I-Al-Istannen) [reply src/main/java/spoon/support/adaption/TypeAdaptor.java]: Addressed (hopefully :P). Thanks :)

File: src/main/java/spoon/support/visitor/java/JavaReflectionTreeBuilder.java [hunk 2]
```diff
@@ -141,6 +136,24 @@ public <T, R extends CtType<T>> R scan(Class<T> clazz) {
...
+		if (javaPackage == null && clazz.isArray()) {
+			javaPackage = getArrayType(clazz).getPackage();
+		}
+		if (javaPackage == null) {
+			return factory.Package().getRootPackage();
+		}
+		return factory.Package().getOrCreate(javaPackage.getName());
+	}
+
+	private static Class<?> getArrayType(Class<?> array) {
```
Comment (SirYwell) [inline src/main/java/spoon/support/visitor/java/JavaReflectionTreeBuilder.java:150]: The naming here is confusing, maybe something like `getInnermostComponentType` would be better?

**Review by SirYwell — CHANGES_REQUESTED** [review]

File: src/main/java/spoon/support/visitor/java/JavaReflectionTreeBuilder.java (hunk 2 above)
Comment (I-Al-Istannen) [reply src/main/java/spoon/support/visitor/java/JavaReflectionTreeBuilder.java:150]: The rest of the code `CtArrayReference` uses the same terminology, so I opted to keep it the same. But I can adjust it, sure :)

Comment (SirYwell) [reply src/main/java/spoon/support/visitor/java/JavaReflectionTreeBuilder.java:150]: I see... well, then it's fine I guess.

**Review by SirYwell — APPROVED** [review]

**Comment by SirYwell** [comment]
Thanks!
