### PR TITLE
fix: records can have static initializers

### LINKED ISSUE #4961: [Bug]: static initializers are forbidden in a record and throw an JLSViolation
### Describe the bug

Java Records allow the inclusion of static fields, static initializers, and static methods. (https://docs.oracle.com/en/java/javase/17/language/records.html or https://openjdk.org/jeps/395)

When programmatically creating a record and adding a static initializer, a JLSViolation Error gets thrown.
The static initializer is wrapped in a CtAnonymousExecutable and is therefore not allowed (See location in code below).

https://github.com/INRIA/spoon/blame/master/src/main/java/spoon/support/reflect/declaration/CtRecordImpl.java#L120

### Source code you are trying to analyze/transform

```Java
record Test(int x) {
    static {
        println("test");
    }
}
```

### Source code for your Spoon processing

```Java
/**
     * Copies all statements that do not need special record treatment.
     */
    private fun copyUnhandledStatements() {
        baseClass.typeMembers
            .filter { d -> d !is CtField<*> && d !is CtMethod<*>}
            .forEach { record.addTypeMember<CtType<Any>>(it) }
    }
```

### Actual output

```Java
Exception in thread "main" spoon.JLSViolation: Anonymous executable is not allowed in a record
	at spoon.JLSViolation.throwIfSyntaxErrorsAreNotIgnored(JLSViolation.java:38)
	at spoon.support.reflect.declaration.CtRecordImpl.addTypeMemberAt(CtRecordImpl.java:120)
	at spoon.support.reflect.declaration.CtTypeImpl.addTypeMember(CtTypeImpl.java:122)
	...
```

### Expected output

_No response_

### Spoon Version

10.1.1

### JVM Version

17

### What operating system are you using?

Ubuntu 22.04

### PR DESCRIPTION
**Pull request by SirYwell**
Fixes #4961

While instance initializers are forbidden, static initializers are allowed.

### CODE REVIEW

File: src/test/java/spoon/test/record/CtRecordTest.java [hunk 1]
```diff
@@ -202,6 +207,15 @@ void testGenericTypeParametersArePrintedBeforeTheFunctionParameters() {
...
 	}
 
+	@Test
+	void testBuildRecordModelWithStaticInitializer() {
+		// contract: a record can have static initializers
+		String code = "src/test/resources/records/WithStaticInitializer.java";
+		CtModel model = assertDoesNotThrow(() -> createModelFromPath(code));
+		List<CtAnonymousExecutable> execs = model.getElements(new TypeFilter<>(CtAnonymousExecutable.class));
+		assertThat(execs.size(), equalTo(2));
+	}
```
Comment (MartinWitt) [inline src/test/java/spoon/test/record/CtRecordTest.java:217]: Maybe use `ModelTest` here?

File: src/main/java/spoon/support/reflect/declaration/CtRecordImpl.java [hunk 2]
```diff
@@ -117,8 +117,8 @@ public <C extends CtType<Object>> C addTypeMemberAt(int position, CtTypeMember m
 			JLSViolation.throwIfSyntaxErrorsAreNotIgnored(this, String.format("%s method is native or abstract, both is not allowed",
 					member.getSimpleName()));
 		}
-		if (member instanceof CtAnonymousExecutable) {
-			JLSViolation.throwIfSyntaxErrorsAreNotIgnored(this, "Anonymous executable is not allowed in a record");
+		if (member instanceof CtAnonymousExecutable && !member.isStatic()) {
+			JLSViolation.throwIfSyntaxErrorsAreNotIgnored(this, "Instance initializer is not allowed in a record");
```
Comment (MartinWitt) [inline src/main/java/spoon/support/reflect/declaration/CtRecordImpl.java:121]: An oversight from myself earlier, we should add the JLS paragraph here. Could you add it?

**Review by MartinWitt — CHANGES_REQUESTED** [review]

File: src/test/java/spoon/test/record/CtRecordTest.java (hunk 1 above)
Comment (SirYwell) [reply src/test/java/spoon/test/record/CtRecordTest.java:217]: As building the model failed, we can't use ModelTest here

**Review by MartinWitt — APPROVED** [review]

**Comment by MartinWitt** [comment]
Impressive high speed at fixing issues, thank @SirYwell. Will merge later today/tomorrow after the 24-hour period. If I forgot to merge it, feel free to ping me.
