### PR TITLE
fix(scanner): Changes all enter/exitReferences inv to enter/exit.

### LINKED ISSUE #437: Changes enter/exitReference to enter/exit in CtScanner for references

### PR DESCRIPTION
**Pull request by GerardPaligot**
Closes #437

### CODE REVIEW

File: src/test/java/spoon/test/template/TemplateTest.java [hunk 1]
```diff
@@ -107,7 +107,8 @@ public void testTemplateC1() throws Exception {
 		assertEquals("return \"testparam2\"", m2.getBody().getStatement(0)
 				.toString());
 
-		new ModelConsistencyChecker(factory.getEnvironment(), false, true).scan(c1);
+		// fixInconsistencies is set to true because references don't have a null parent.
```
Comment (monperrus) [inline src/test/java/spoon/test/template/TemplateTest.java]: > because references don't have a null parent.
This is surprising.

All references now have a parent right?

Comment (GerardPaligot) [inline src/test/java/spoon/test/template/TemplateTest.java]: Yes, they have a parent. Before the application of the scanner `ModelConsistencyChecker`, the parent of references are elements of the template. The scanner set the parent after the substitution of templates and put the target parent in references.

**Comment by GerardPaligot** [comment]
@monperrus PR ok.
