### PR TITLE
Fixes BlockTemplate and adds replace in CtElement

### LINKED ISSUE #508: add again CtElement.replace

### PR DESCRIPTION
**Pull request by GerardPaligot**
Closes #508

### CODE REVIEW

File: src/test/java/spoon/test/template/TemplateTest.java [hunk 1]
```diff
@@ -217,4 +222,18 @@ public void testTemplateMatcher() throws Exception {
...
 
+	@Test
+	public void testExtensionBlock() throws Exception {
+		final Launcher launcher = new Launcher();
+		launcher.addInputResource("./src/test/java/spoon/test/template/Logger.java");
+		launcher.addInputResource("./src/test/java/spoon/test/template/LoggerTemplate.java");
+		launcher.setSourceOutputDirectory("./target/trash");
+		launcher.addProcessor(new LoggerTemplateProcessor());
+		launcher.getEnvironment().setSourceClasspath(System.getProperty("java.class.path").split(File.pathSeparator));
+		try {
```
Comment (monperrus) [inline src/test/java/spoon/test/template/TemplateTest.java]: add assertion on the resulting model?

Comment (GerardPaligot) [inline src/test/java/spoon/test/template/TemplateTest.java]: Done.
