### PR TITLE
fix:Removing the use of 3rd party internal constants

### LINKED ISSUE #3185: Get rid of TypeConstants.MODULE_INFO_FILE_NAME in our code
As mentioned by @m-manseer in https://github.com/INRIA/spoon/issues/3009#issuecomment-560355642 this field is part of an internal API that should not be accessed.
We should instead just declare our own field for this value "module-info.java".

### PR DESCRIPTION
**Pull request by m-manseer**
All uses of constants defined in `org.eclipse.jdt.internal.compiler.lookup.TypeConstants`, which is an internal class, are replaced by custom defined constants. Closes #3185.

### CODE REVIEW

File: src/main/java/spoon/support/compiler/jdt/JDTConstants.java [hunk 1]
```diff
@@ -0,0 +1,17 @@
...
+ */
+package spoon.support.compiler.jdt;
+
+/**
+ * Extracts a subset of constants as defined in {@link org.eclipse.jdt.internal.compiler.lookup.TypeConstants}, since
+ * this class is only meant for internal use.
+ */
+public class JDTConstants {
+
+    public static final char[] MODULE_INFO_FILE_NAME = "module-info.java".toCharArray();
```
Comment (surli) [inline src/main/java/spoon/support/compiler/jdt/JDTConstants.java]: Spoon uses tabs for tabulations. Right now the build fails because of the checkstyle:
> [ERROR] /home/travis/build/INRIA/spoon/src/main/java/spoon/support/compiler/jdt/JDTConstants.java:15: Indent must use tab characters [RegexpSinglelineJava]

Moreover you should provide a default private constructor for it:
> [ERROR] /home/travis/build/INRIA/spoon/src/main/java/spoon/support/compiler/jdt/JDTConstants.java:12:1: Utility classes should not have a public or default constructor. [HideUtilityClassConstructor]

File: src/main/java/spoon/support/compiler/jdt/JDTConstants.java [hunk 2]
```diff
@@ -0,0 +1,19 @@
...
+ */
+package spoon.support.compiler.jdt;
+
+/**
+ * Extracts a subset of constants as defined in {@link org.eclipse.jdt.internal.compiler.lookup.TypeConstants}, since
+ * this class is only meant for internal use.
+ */
+public class JDTConstants {
+
+	private JDTConstants() {}
```
Comment (surli) [inline src/main/java/spoon/support/compiler/jdt/JDTConstants.java]: Still some complains from checkstyle:
> ERROR] /home/travis/build/INRIA/spoon/src/main/java/spoon/support/compiler/jdt/JDTConstants.java:14:33: '{' is not followed by whitespace. [WhitespaceAround]
[ERROR] /home/travis/build/INRIA/spoon/src/main/java/spoon/support/compiler/jdt/JDTConstants.java:14:33: '}' is not preceded with whitespace. [WhitespaceAround]

**Comment by surli** [comment]
@monperrus merge?

**Comment by monperrus** [comment]
Thanks a lot for your contribution!

**Comment by m-manseer** [comment]
@monperrus You're very welcome.
