### PR TITLE
fix(comment): support comment on string concatenation

### LINKED ISSUE #1123: ParentNotInitializedException on CtComments
Hello, 

When I build JavaFileTest from javapoet with comments enabled, the build throw me the following error:
```
017-01-17 09:26:51,496 ERROR spoon.support.compiler.jdt.JDTCommentBuilder - // Second 'Float' is fully qualified. is not added into the AST
spoon.reflect.declaration.ParentNotInitializedException: parent not initialized for class spoon.support.reflect.code.CtCommentImpl (/home/bdanglot/workspace/spoon/src/test/resources/JavaFileTest.java:309)
	at spoon.support.reflect.declaration.CtElementImpl.getParent(CtElementImpl.java:294)
	at spoon.support.compiler.jdt.JDTCommentBuilder.insertCommentInAST(JDTCommentBuilder.java:394)
	at spoon.support.compiler.jdt.JDTCommentBuilder.buildComment(JDTCommentBuilder.java:133)
	at spoon.support.compiler.jdt.JDTCommentBuilder.build(JDTCommentBuilder.java:98)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildModel(JDTBasedSpoonCompiler.java:428)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildUnitsAndModel(JDTBasedSpoonCompiler.java:375)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildSources(JDTBasedSpoonCompiler.java:348)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:119)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:102)
	at spoon.Launcher.buildModel(Launcher.java:700)
	at spoon.Test.testComments(Test.java:18)
```

snippet example:

```java
assertThat(source).isEqualTo(""
        + "  com.squareup.soda.Float beverage;\n" // Second 'Float' is fully qualified.
        + "}\n")
```

### PR DESCRIPTION
**Pull request by tdurieux**
fix #1123

### CODE REVIEW

File: src/test/java/spoon/test/comment/CommentTest.java [hunk 1]
```diff
@@ -263,7 +264,12 @@ public void testInLineComment() {
...
 
 
-		CtReturn ctReturn = m1.getBody().getStatement(12);
+		CtLocalVariable ctLocalVariableString = m1.getBody().getStatement(12);
+		assertEquals(createFakeComment(f, "comment multi line string"), ((CtBinaryOperator)((CtBinaryOperator)ctLocalVariableString.getDefaultExpression()).getRightHandOperand()).getLeftHandOperand().getComments().get(0));
+		assertEquals("\"\" + (\"\"// comment multi line string" + newLine
+				+ " + \"\")", ctLocalVariableString.getDefaultExpression().toString());
+
+		CtReturn ctReturn = m1.getBody().getStatement(13);
 		assertEquals(createFakeComment(f, "comment return"), ctReturn.getComments().get(0));
```
Comment (surli) [inline src/test/java/spoon/test/comment/CommentTest.java]: I'm not sure to understand the relation between your changes and the new test: you change the behaviour of comments for conditionnals, if and executables and you test a multiline string?... I think I miss something.

Comment (tdurieux) [inline src/test/java/spoon/test/comment/CommentTest.java]: It is complex...
Now I print comments of CtExpression.

These lines was basically there to handle CtExpressions present in CtConditional (may not work for other expression).
```java
if (!(thenExpression instanceof CtStatement)) {		
 	elementPrinterHelper.writeComment(thenExpression, CommentOffset.BEFORE);		
}
```
Now I handle the comment of every CtExpression.

More over I added a position for the string concatenation.
This way JDTCommentBuilder is able to handle the comment in string.
