### PR TITLE
review: fix: set correct executable reference type for signature polymorphic methods

### LINKED ISSUE #4863: [Bug]: Inconsistency in modelling of invocations of signature polymorphic methods
### Describe the bug

*Another sweet, very specific edge case*
Java has a few [signature polymorphic methods](https://docs.oracle.com/javase/specs/jls/se18/html/jls-15.html#jls-15.12.3).

In my opinion, there are two ways how spoon could model invocations of such methods:

1. Use the return type and the the `Object...` (or `Object[]`) type parameter of the declared method
2. Use the return type and the parameters from the invocation context as described in the JLS.

However, spoon currently picks the third one: The return type is invocation-specific but the parameter is always `Object[]`.

Both solutions are possible as JDT provides the needed information. This issue is rather for discussion which solution is more appropriate for spoon.

### Source code you are trying to analyze/transform

```Java
package invoke;

import spoon.Launcher;
import spoon.reflect.CtModel;
import spoon.reflect.code.CtInvocation;
import spoon.reflect.declaration.CtMethod;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.MethodHandles;

public class SignaturePolymorphic {
  private static final MethodHandle MH = MethodHandles.identity(String.class);
  public static void main(String[] args) throws Throwable {
    Launcher launcher  = new Launcher();
    launcher.addInputResource("src/main/java/invoke/SignaturePolymorphic.java");
    launcher.getEnvironment().setComplianceLevel(17);
    CtModel ctModel = launcher.buildModel();
    for (CtMethod<?> method : ctModel.getAllTypes().iterator().next().getMethodsByName("a")) {
      CtInvocation<?> lastStatement = method.getBody().getLastStatement();
      lastStatement = (CtInvocation<?>) lastStatement.getArguments().get(0);
      System.out.println(lastStatement.getType());
      System.out.println(lastStatement.getExecutable().getParameters());
    }
  }

  private void a() throws Throwable {
    System.out.println((String) MH.invoke("Hello World"));
  }
}
```

### Source code for your Spoon processing

```Java
(contained in the example above)
```

### Actual output

```Java
java.lang.String
[java.lang.Object[]]
```

### Expected output

```Java
Either

java.lang.String
[java.lang.String]

or

java.lang.Object
[java.lang.Object[]]
```

### Spoon Version

10.2.0-beta-16

### JVM Version

17

### What operating system are you using?

Windows 11

### PR DESCRIPTION
**Pull request by SirYwell**
Fixes #4863 

As we decided to go the easier route, the change is pretty straightforward: We only need to correct the return type of the reference to always be `java.lang.Object`.

### CODE REVIEW

**Comment by SirYwell** [comment]
Let the review begin :)

File: src/main/java/spoon/support/compiler/jdt/ReferenceBuilder.java [hunk 1]
```diff
@@ -453,6 +453,12 @@ <T> CtExecutableReference<T> getExecutableReference(MethodBinding exec, int sour
 
 		// original() method returns a result not null when the current method is generic.
 		if (exec.original() != null) {
+			// if polymorphic, the original return type differs from the actual return type
+			//  therefore we use the original one here
+			//  see https://github.com/INRIA/spoon/issues/4863
+			if (exec.isPolymorphic()) {
+				ref.setType(getTypeReference(exec.original().returnType, true));
```
Comment (I-Al-Istannen) [inline src/main/java/spoon/support/compiler/jdt/ReferenceBuilder.java:460]:
```suggestion
				ref.setType(getTypeReference(exec.original().returnType));
```
Why do we need to resolve generics here?

**Review by I-Al-Istannen — APPROVED** [review]

**Comment by monperrus** [comment]
thanks a lot @SirYwell
