### PR TITLE
fix: update the level of unwanted info logs to debug

### LINKED ISSUE #4250: Make the check mojo less verbose by default
```
[INFO] --- spoon-maven-plugin:3.5:check (spoon-test) @ xwiki-commons-blame-api ---
[INFO] Running in FULLCLASSPATH mode (doc: http://spoon.gforge.inria.fr/launcher.html).
[INFO] Spoon version ${project.version}
[INFO] running Spoon...
[INFO] start processing...
[INFO] org.xwiki.tool.spoon.JUnit5JUnit4Processor
[INFO] end of processing: 
[INFO] no errors, no warnings
```

This increases a lot the XWiki build logs unnecessarily. We don't need this since the information is already contained in the spoon configuration we set (you could decide to output them when they're not specified maybe). 

I would remove:
- `Running in FULLCLASSPATH mode (doc: http://spoon.gforge.inria.fr/launcher.html).``
- ` Spoon version ${project.version}`
- ```
  start processing...
  org.xwiki.tool.spoon.JUnit5JUnit4Processor
  end of processing: 
  no errors, no warnings
  ```

I'd just keep `Running Spoon...` (uppercase `R` BTW ;)) to indicate it's executing. If there are warnings or errors, I guess they'll be displayed so no need to say there were no errors.

Also all these info should be displayed when Maven is executed in debug mode (`-X`).

WDYT?

Thanks

### PR DESCRIPTION
**Pull request by yogyagamage**
- Fixes #4250

### CODE REVIEW

**Review by MartinWitt — APPROVED** [review]

**Comment by MartinWitt** [comment]
LGTM, will merge.

File: src/test/java/spoon/test/logging/LogTest.java [hunk 1]
```diff
@@ -74,7 +74,7 @@ public void testAllLevelsForLogs(Pair<Level, Integer> levelAndExpectedCount) {
 	private static Stream<Pair<Level, Integer>> getLogLevelsAndExpectedCounts() {
 		return Stream.of(
 				Pair.of(Level.DEBUG, 6),
```
Comment (algomaster99) [inline src/test/java/spoon/test/logging/LogTest.java:76]:
```suggestion
				Pair.of(Level.DEBUG, 7),
```

Intuitively speaking, should this not be incremented by 1 as some levels of some log statement is replaced by `DEBUG`? I may be wrong. It would be nice to approve workflow run after [`18dbb3d` (#5312)](https://github.com/INRIA/spoon/pull/5312/commits/18dbb3d1c7898b502bea6f506d13bb609653f9a5).

**Comment by monperrus** [comment]
thanks @yogyagamage
