### PR TITLE
fix: convert floating types not to long during simplifcation

### LINKED ISSUE #5047: [Bug]: `VisitorPartialEvaluator` removes decimals of negated `float` and `double` literals
### Describe the bug

The `VisitorPartialEvaluator` and the method `CtCodeElement#partiallyEvaluate` that uses it incorrectly transforms number literals to which the unary negation operator is applied.

Due to the following usage of `longValue` for all number literals, the decimal places of `float` and `double` literals are lost when applying an unary negation operator to them:

https://github.com/INRIA/spoon/blob/f6a61754624df8ec2a8057f34dbdbf6db70b8989/src/main/java/spoon/support/reflect/eval/VisitorPartialEvaluator.java#L556-L558

And the following function `convert` does not handle the type `double`, so the resulting literal will be of type `long` instead:

https://github.com/INRIA/spoon/blob/f6a61754624df8ec2a8057f34dbdbf6db70b8989/src/main/java/spoon/support/reflect/eval/VisitorPartialEvaluator.java#L65-L82

### Source code you are trying to analyze/transform

```Java
public class Test {
	static double test() {
		System.out.println(-1.234567);
		System.out.println(-2.345f);
		System.out.println(-3);
		System.out.println(-4L);
	}
}
```

### Source code for your Spoon processing

```Java
Launcher spoon = new Launcher();
spoon.addInputResource(new VirtualFile(...));
CtModel model = spoon.buildModel();
CtMethod<?> method = model.getElements(new TypeFilter<>(CtMethod.class)).get(0);
System.out.println(method);
method.setBody(method.getBody().partiallyEvaluate());
System.out.println(method);
```

### Actual output

```Java
static double test() {
    System.out.println(-1.234567);
    System.out.println(-2.345F);
    System.out.println(-3);
    System.out.println(-4L);
}
static double test() {
    System.out.println(-1L);
    System.out.println(-2.0F);
    System.out.println(-3);
    System.out.println(-4L);
}
```

### Expected output

```Java
static double test() {
    System.out.println(-1.234567);
    System.out.println(-2.345F);
    System.out.println(-3);
    System.out.println(-4L);
}
static double test() {
    System.out.println(-1.234567);
    System.out.println(-2.345F);
    System.out.println(-3);
    System.out.println(-4L);
}
```

### Spoon Version

10.2.0

### JVM Version

17

### What operating system are you using?

Windows 10 64 bit

### PR DESCRIPTION
**Pull request by MartinWitt**
fixes #5047

### CODE REVIEW

File: src/main/java/spoon/support/reflect/eval/VisitorPartialEvaluator.java [hunk 1]
```diff
@@ -566,6 +572,22 @@ public <T> void visitCtUnaryOperator(CtUnaryOperator<T> operator) {
 		setResult(operator.clone());
 	}
 
+	/**
+	 * Checks if the given type reference is a floating type. This includes both primitive and non-primitive types.
```
Comment (I-Al-Istannen) [inline src/main/java/spoon/support/reflect/eval/VisitorPartialEvaluator.java:576]:
```suggestion
	 * Checks if the given type reference is a floating type. This includes primitives and their wrapper types.
```

File: src/main/java/spoon/support/reflect/eval/VisitorPartialEvaluator.java [hunk 2]
```diff
@@ -566,6 +572,22 @@ public <T> void visitCtUnaryOperator(CtUnaryOperator<T> operator) {
...
+	 * A type is considered floating if it is either a double or a float.
```
Comment (I-Al-Istannen) [inline src/main/java/spoon/support/reflect/eval/VisitorPartialEvaluator.java:577]:
```suggestion
	 * A type is considered floating iff it is {@code double} or  {@code float}.
```

File: src/test/java/spoon/test/eval/EvalTest.java [hunk 3]
```diff
@@ -311,7 +315,35 @@ public void testconvertElementToRuntimeObject() {
...
+	"-3        | -3 		  ",
+	"-4L 		   | -4L       "})
+	void testDoublePrecisionLost(String literal, String expected) {
+		// contract: the partial evaluation of a binary operator on literals does not lose precision for double and float
+		String code = "public class Test {"
+	 	+ "double test() {"
+		+ "	System.out.println(%s);"
+ 		+ "}"
+ 		+ "};";
+		Launcher spoon = new Launcher();
```
Comment (I-Al-Istannen) [inline src/test/java/spoon/test/eval/EvalTest.java:341]: `Launcher.parseClass` might fit better? I don't know.

File: src/test/java/spoon/test/eval/EvalTest.java [hunk 4]
```diff
@@ -311,7 +315,35 @@ public void testconvertElementToRuntimeObject() {
...
+	@ParameterizedTest
+	@CsvSource(
+	delimiter = '|',
+	useHeadersInDisplayName = true,
+	value = {
+	" Literal  | Expected ",	
+	"-1.234567 | -1.234567",
+	"-2.345F   | -2.345F   ", 
+	"-3        | -3 		  ",
+	"-4L 		   | -4L       "})
```
Comment (I-Al-Istannen) [inline src/test/java/spoon/test/eval/EvalTest.java:333]: This looks odd. Maybe this instead?
```suggestion
	@CsvSource(
		delimiter = '|',
		useHeadersInDisplayName = true,
		value = {
			" Literal  | Expected ",	
			"-1.234567 | -1.234567",
			"-2.345F   | -2.345F   ", 
			"-3        | -3 		  ",
			"-4L 		   | -4L       "
		}
	)
```

**Review by I-Al-Istannen — DISMISSED** [review]
Some formatting questions, but looks fine

**Review by I-Al-Istannen — APPROVED** [review]

File: src/test/java/spoon/test/eval/EvalTest.java [hunk 5]
```diff
@@ -311,7 +315,34 @@ public void testconvertElementToRuntimeObject() {
...
+			"-2.345F   | -2.345F   ", 
+			"-3        | -3 		  ",
+			"-4L 		   | -4L       "
+		}
+	)
+	void testDoublePrecisionLost(String literal, String expected) {
+		// contract: the partial evaluation of a binary operator on literals does not lose precision for double and float
+		String code = "public class Test {"
+	 	+ "double test() {"
+		+ "	System.out.println(%s);"
```
Comment (I-Al-Istannen) [inline src/test/java/spoon/test/eval/EvalTest.java:340]: This method does not compile.

**Review by I-Al-Istannen — CHANGES_REQUESTED** [review]

**Review by I-Al-Istannen — APPROVED** [review]
