### PR TITLE
review: fix: compiled snippets have no parent

### LINKED ISSUE #2318: bug? About the usage of CtCodeSnippetStatement
I just found in https://github.com/SpoonLabs/astor/pull/112 that @martinezmatias was using `CtCodeSnippetStatement` in given more that one statement at a time, and it was working in 6.2.0 but apparently no more in 7.0.0. 

Here's an example of the test and its behaviour in Spoon 7.0.0:

```java
String snippet = "int n=0; n += 2";
Factory factory = new FactoryImpl(new DefaultCoreFactory(), new StandardEnvironment());
CtStatement st = factory.Code().createCodeSnippetStatement(snippet).compile();

System.out.println(st.toString()); // n += 2;
CtElement fix = ((CtBlock) st.getParent()).getStatement(1); // indexOutOfBoundsException : there's only one statement
```

So apparently there's a bug here because the second statement indeed have the block as parent, but is not included as a statement of the block. 

Now the question is: should a `CtCodeSnippetStatement` accept to get more that one statement? Shouldn't we create a new element `CtCodeSnippetBlock` to those cases? 

I'm really not a user of those features in Spoon so I need your vision on this one.

### PR DESCRIPTION
**Pull request by monperrus**
fix #2318

### CODE REVIEW

File: src/test/java/spoon/test/serializable/SerializableTest.java [hunk 1]
```diff
@@ -25,39 +25,34 @@
...
-		assertNotNull(typeDes);
-		//After deserialization, getDeclaringType throws an exception
-		CtType<?> decl =  typeDes.getDeclaringType();
-		assertNull(decl);
-
-		CtPackage parentOriginal = (CtPackage) typeBef.getParent();
-		CtPackage parentDeser = (CtPackage) typeDes.getParent();
-
-		assertEquals(CtPackage.TOP_LEVEL_PACKAGE_NAME,parentOriginal.getSimpleName());
+		CtType<?> typeDes = deserializedSta2.getParent(CtType.class);
```
Comment (pvojtechovsky) [inline src/test/java/spoon/test/serializable/SerializableTest.java]: `assertFalse(deserializedSta2.isParentInitialized());` WDYT?

Comment (monperrus) [reply src/test/java/spoon/test/serializable/SerializableTest.java]: done

**Comment by pvojtechovsky** [comment]
Thank you Martin
