### PR TITLE
review refactor: getBoundingType now returns Object by default

### LINKED ISSUE #1666: CtTypeParameterReference#getBoundingType() should return Object appropriately
CtTypeParameterReference#getBoundingType() should always return Object reference when bounding type is null or Object

spin-off of #1661

### LINKED ISSUE #1670: bug: Regression with the use of generics
Apparently we got a regression with generics maybe because of #1661 
We got the following error when using Spoon on assertj: 

> Failed to execute goal fr.inria.gforge.spoon:spoon-maven-plugin:2.4:generate (default) on project assertj-core: Exception during the spoonify of the target project. Type mismatch: cannot convert from AbstractListAssert<capture#76-of ?,List<? extends Object>,Object,ObjectAssert<Object>> to AbstractListAssert<?,List<?>,Object,ObjectAssert<Object>> at /builds/workspace/AssertJ/src/main/java/org/assertj/core/api/AbstractIterableAssert.java:491 -> [Help 1]

Full log available there: https://ci.inria.fr/sos/job/AssertJ/428/console

### PR DESCRIPTION
**Pull request by surli**
Instead of returning null, default behaviour of getBoundingType is to return Object. 
This PR is an alternative to #1661

Fix #1670
Fix #1666

### CODE REVIEW

File: src/main/java/spoon/support/reflect/reference/CtTypeParameterReferenceImpl.java [hunk 1]
```diff
@@ -50,6 +50,7 @@
 
 	public CtTypeParameterReferenceImpl() {
 		super();
+		this.setBoundingType(getFactory().Type().objectType()); // by default set bounding type to object
```
Comment (pvojtechovsky) [inline src/main/java/spoon/support/reflect/reference/CtTypeParameterReferenceImpl.java]: we should create new CtTypeReference, because AST should not share nodes

File: src/main/java/spoon/support/reflect/reference/CtTypeParameterReferenceImpl.java [hunk 2]
```diff
@@ -173,6 +164,13 @@ public boolean removeBound(CtTypeReference<?> bound) {
 		if (superType != null) {
 			superType.setParent(this);
 		}
+
+		// ugly but else make testSetterInNodes failed
+		if (superType == null) { // if null, set bounding type to object
+			superType = getFactory().Type().objectType();
+			superType.setParent(this);
```
Comment (pvojtechovsky) [inline src/main/java/spoon/support/reflect/reference/CtTypeParameterReferenceImpl.java]: use new CtTypeReference too

**Comment by pvojtechovsky** [comment]
This PR is compatible with algorithms, which needed fast fix #1661. This solution is on good way. I like it!

**Comment by monperrus** [comment]
I like it too! `return null` is always such a bad idea!

File: src/main/java/spoon/support/reflect/reference/CtTypeParameterReferenceImpl.java (hunk 1 above)
Comment (surli) [reply src/main/java/spoon/support/reflect/reference/CtTypeParameterReferenceImpl.java]: Actually the methods already create a clone of OBJECT in `TypeFactory`, see: https://github.com/INRIA/spoon/blob/e2e359e2e59c23a94cd042a6851e8058cd62dc5c/src/main/java/spoon/reflect/factory/TypeFactory.java#L250

So I assume the nodes are not shared.

Comment (pvojtechovsky) [reply src/main/java/spoon/support/reflect/reference/CtTypeParameterReferenceImpl.java]: you are right. I did not knew that. So it is OK

**Comment by surli** [comment]
**Any help is welcome for that PR!**

The changes are done for passing the current Spoon test suite, but I don't manage to fix #1670 or to reproduce it in a small unit test.
The bug occured when using the script https://github.com/INRIA/spoon/blob/master/doc/jenkins/build.sh on assertj-core project. I now got the following error:

>  Failed to execute goal fr.inria.gforge.spoon:spoon-maven-plugin:2.4:generate (default) on project assertj-core: Exception during the spoonify of the target project.: Type mismatch: cannot convert from AbstractListAssert<capture#76-of ?,List<? extends Object>,Object,ObjectAssert<Object>> to AbstractListAssert<?,List<?>,Object,ObjectAssert<Object>> at /Users/urli/Github/assertj-core/src/main/java/org/assertj/core/api/AbstractIterableAssert.java:491

I manage to fix the bug manually by changing `AbstractListAssert<?,List<?>,Object,ObjectAssert<Object>>` to `AbstractListAssert<?,List<? extends java.lang.Object>,Object,ObjectAssert<Object>>` manually in the code, but I don't completely understand why explicitely extending the wildcard to object in the source code fix the bug. 
I think it's because this method use another method which have the following return signature:
`AbstractListAssert<?,List<? extends E>,Object,ObjectAssert<E>>` and JDT does not manage to make the binding properly, but I still did not manage to reproduce the bug yet.

Still, my manual bug fix seems to show that sometimes we need to explicitely output an `extends Object`. Then I may need to know when there was an explicit extends object in source, and when it was implicit. Any idea to fix that?

File: src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java [hunk 3]
```diff
@@ -618,7 +618,7 @@ public void visitCtTypeParameter(CtTypeParameter typeParameter) {
 		} else {
 			printer.writeIdentifier(ref.getSimpleName());
 		}
-		if (ref.getBoundingType() != null) {
+		if (ref.getBoundingType() != null && !ref.getBoundingType().equals(ref.getFactory().Type().OBJECT)) { // we ignore printing "extends Object"
```
Comment (monperrus) [inline src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java]: one solution may be to simply remove this and always write "extends Object"

Comment (pvojtechovsky) [reply src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java]: I vote for shorter printed source code. So never print "... extends Object"

Comment (surli) [reply src/main/java/spoon/reflect/visitor/DefaultJavaPrettyPrinter.java]: > So never print "... extends Object"

And then I have a bug with assertj-core.

**Comment by surli** [comment]
So... in fact as here as in #1202 the bug is related to JDT own interpretation of wildcard generics in Java. 
If you take this line https://github.com/joel-costigliola/assertj-core/blob/9d45e93be7f41da5c0709fc852bebd4ef79f6162/src/main/java/org/assertj/core/api/AbstractIterableAssert.java#L1435

in Intellij Idea it shows a warning on  `? extends Object` saying its redundant, and in Eclipse it shows an error when you remove the extends. 
Then as I already said, here the only way to fix the bug is to have a way to know if this extends belongs to the original source code or not.

**Comment by monperrus** [comment]
OracleJDK and OpenJDK don't handle generics the same way, and this is yet another instance of the
problem.

> Then as I already said, here the only way to fix the bug is to have a way to know if this extends
> belongs to the original source code or not.
We have isImplicit that we can put in the bounding type.

--Martin

**Comment by surli** [comment]
> We have isImplicit that we can put in the bounding type.
I'll take a look on that.

**Comment by surli** [comment]
The last changes now fix the error in #1670 we use the `isImplicit` to tell DJPP if it must be output or not.

File: src/main/java/spoon/reflect/reference/CtTypeParameterReference.java [hunk 4]
```diff
@@ -99,4 +99,10 @@
 	@Override
 	@UnsettableProperty
 	<T extends CtActualTypeContainer> T setActualTypeArguments(List<? extends CtTypeReference<?>> actualTypeArguments);
+
+	/**
+	 * Returns true if the given typeReference is the default bounding type (i.e. java.lang.Object)
+	 */
+	@DerivedProperty
+	boolean isDefaultBoundingType(CtTypeReference typeReference);
```
Comment (monperrus) [inline src/main/java/spoon/reflect/reference/CtTypeParameterReference.java]: parameter needed? could be simply `isDefaultBound()` with no parameter?

File: src/test/java/spoon/test/reference/TypeReferenceTest.java [hunk 5]
```diff
@@ -510,15 +510,17 @@ public void testClearBoundsForTypeParameterReference() throws Exception {
...
 		reference.addBound(factory.Type().createReference(String.class));
 
 		assertNotNull(reference.getBoundingType());
 
 		reference.setBounds(new ArrayList<>());
 
-		assertNull(reference.getBoundingType());
+		assertEquals(factory.Type().OBJECT, reference.getBoundingType());
+		assertTrue(reference.isDefaultBoundingType(reference.getBoundingType()));
 	}
```
Comment (monperrus) [inline src/test/java/spoon/test/reference/TypeReferenceTest.java]: add a test corresponding to the assert4j problem?

File: src/main/java/spoon/reflect/reference/CtTypeParameterReference.java (hunk 4 above)
Comment (surli) [reply src/main/java/spoon/reflect/reference/CtTypeParameterReference.java]: The parameter is needed for case like https://github.com/INRIA/spoon/pull/1672/files#diff-e14ef777963d781b479e6fdd3e8d419dR79 where we want to check before setting the boundingType.

File: src/test/java/spoon/test/reference/TypeReferenceTest.java (hunk 5 above)
Comment (surli) [reply src/test/java/spoon/test/reference/TypeReferenceTest.java]: > add a test corresponding to the assert4j problem?

I cannot reproduce exactly the assert4j problem, but we already have in our test a case with an explicit "? super Object", I changed the assert accordingly: https://github.com/INRIA/spoon/pull/1672/files#diff-c20710bb8ee877d0eae2d22578a8f010R506

**Comment by monperrus** [comment]
I'm not convinced by the design and the encapsulation of this new method. Can the the test be rewritten?

**Comment by surli** [comment]
> I'm not convinced by the design and the encapsulation of this new method. Can the the test be rewritten?

You're talking about `CtTypeParameterReference#isDefaultBoundingType`, right?
I'm completely open to redesign it, but I'm not sure to understand what you want.

**Comment by monperrus** [comment]
I'd propose to remove the parameter of the method. the "is" applied to "this".

File: src/main/java/spoon/reflect/reference/CtTypeParameterReference.java (hunk 4 above)
Comment (pvojtechovsky) [reply src/main/java/spoon/reflect/reference/CtTypeParameterReference.java]: The code on the link will work if object is sent to adapt method too. Only check for null is needed.
The implementation of `is default bounding type` can be made static. May be we do not need such method at all.

**Comment by surli** [comment]
> I'd propose to remove the parameter of the method. the "is" applies to "this" not to the parameter.

I'm ok with that but I also want to have a place where the default value of boundingType is defined and that I can use without creating a new CtTypeParameterReference object. This will allow me to do some checks with a single point of definition for the default value of bounding type. 

Where do you think I can create such a method?

**Comment by monperrus** [comment]
In a helper class with only static methods? such as JDTTreeBuilderHelper?

**Comment by surli** [comment]
It's ready for merging

**Comment by monperrus** [comment]
Thanks a lot.
