### PR TITLE
fix(noclasspath): Creates type reference from string and JDT ref.

### LINKED ISSUE #479: NullPointerException in JDTTreeBuilder
I am getting the following exception when building a model (with `setNoClasspath(true)`) for a project of mine, using the current master branch at 58b6a5d2ce557d779b3cb9f350c3ba603f4e255c : 

```
Exception in thread "main" java.lang.NullPointerException
	at spoon.support.compiler.jdt.JDTTreeBuilder.insertGenericTypesInNoClasspathFromJDTInSpoon(JDTTreeBuilder.java:1126)
	at spoon.support.compiler.jdt.JDTTreeBuilder.createType(JDTTreeBuilder.java:1095)
	at spoon.support.compiler.jdt.JDTTreeBuilder.visit(JDTTreeBuilder.java:3239)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.traverse(TypeDeclaration.java:1430)
	at spoon.support.compiler.jdt.JDTTreeBuilder.visit(JDTTreeBuilder.java:3281)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.traverse(TypeDeclaration.java:1319)
	at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.traverse(CompilationUnitDeclaration.java:748)
	at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.traverse(CompilationUnitDeclaration.java:709)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildSources(JDTBasedSpoonCompiler.java:228)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:481)
...
```

### PR DESCRIPTION
**Pull request by GerardPaligot**
Closes #479

### CODE REVIEW

File: src/test/java/spoon/test/constructorcallnewclass/NewClassTest.java [hunk 1]
```diff
@@ -157,7 +157,7 @@ public void testCtNewClassInNoClasspath() throws Exception {
 		final CtClass anonymousClass = ctNewClass.getAnonymousClass();
 		assertNotNull(anonymousClass);
 		assertNotNull(anonymousClass.getSuperclass());
-		assertEquals("Lock.With", anonymousClass.getSuperclass().getSimpleName());
```
Comment (monperrus) [inline src/test/java/spoon/test/constructorcallnewclass/NewClassTest.java]: add an assertion on getSimpleName() as well? (I guess it should be "With" or "Lock")

Comment (GerardPaligot) [inline src/test/java/spoon/test/constructorcallnewclass/NewClassTest.java]: Done.
