### PR TITLE
fix: escape sequences in text-blocks are kept

### LINKED ISSUE #4408: [Bug] escape sequences in text-blocks are not retained
**Describe the bug**
Escape sequences in text-blocks are replaced whereas they should be retained.

**To Reproduce**

Input:
```java
    void m5() {
    	String escape = """
    	no-break space: \\00a0
    	newline:        \\n
    	tab:            \\t ('\t')
    	""";
    }
```

Processing with Spoon:
```java
		Launcher launcher = setUpTest();
		launcher.getEnvironment().setAutoImports(true);
		
		CtClass<?> allstmt = (CtClass<?>) launcher.getFactory().Type().get("textBlock.TextBlockTestClass");
		CtMethod<?> m5 =  allstmt.getMethod("m5");

		String m5Text = m5.toString();
```

Output:
```java
    void m5() {
    	String escape = """
    	no-break space: \00a0
    	newline:        \n
    	tab:            \t ('	')
    	""";
    }
```

I will link a PR reproducing this.

**Operating system, JDK and Spoon version used**

* OS:    MacOS 12.1
* JDK:  OpenJDK Runtime Environment GraalVM 21.3.0 (build 17.0.1+12-LTS)
* Spoon version: currrent Git

### PR DESCRIPTION
**Pull request by xzel23**
Fixes #4408
Besides adding the (currently disabled) test case, I changed the Junit imports and fixed the parameter order of the assertEquals calls.

### CODE REVIEW

**Comment by xzel23** [comment]
The failure in the "Extra Checks" step seems to be a technical problem and not related to the changes:
`Error:  OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended`

File: src/main/java/spoon/reflect/visitor/LiteralHelper.java [hunk 1]
```diff
@@ -58,12 +58,11 @@ private static String getBasedString(Double value, LiteralBase base) {
 
 	/**
 	 * @param literal CtTextBlock to be converted
-	 * @param numTabs
 	 * @return source code representation of the literal
 	 */
 	public static String getTextBlockToken(CtTextBlock literal) {
 		String token = "\"\"\"\n"
-				+ literal.getValue()
+				+ literal.getValue().replaceAll("\\\\", "\\\\\\\\")
```
Comment (MartinWitt) [inline src/main/java/spoon/reflect/visitor/LiteralHelper.java:65]: Why does this work?

Comment (xzel23) [reply src/main/java/spoon/reflect/visitor/LiteralHelper.java:65]: It escapes each single backslash by replacing it with a double backslash. It just looks weird because each backslash has to be escaped twice, once for the string literal and then again in the regular expression.

Comment (algomaster99) [reply src/main/java/spoon/reflect/visitor/LiteralHelper.java:65]: > It escapes each single backslash by replacing it with a double backslash.

Would it not be sufficient to write `.replaceAll("\". "\\")`? This is what I can infer from your explanation.

**Comment by algomaster99** [comment]
Fixes #4408 

Add this comment to link the issue to this PR.

File: src/main/java/spoon/reflect/visitor/LiteralHelper.java (hunk 1 above)
Comment (xzel23) [reply src/main/java/spoon/reflect/visitor/LiteralHelper.java:65]: @algomaster99 no, that's a compile time error. The backslash inside the quotes has to be escaped. Then you have a regex consisting of only a backslash. That is an error because the backslash has to be escaped in the regex. So you need another backslash escaping that one, which has to be escaped inside the quotes. That's why you need four backslashes to represent a single backslash in the search regex.

The same then applies for the replacement, so this makes it four backslashes in the search string and eight backslashes in the replacement string.

But you have a point in that we don't need really a regex here. So we can use `String.replace(CharSequence, CharSequence)` instead (note the different method name), which does not use regular expressions. This will be both faster and require only half the escaping. I have updated the PR.

File: src/test/java/spoon/test/textBlocks/TextBlockTest.java [hunk 2]
```diff
@@ -118,4 +119,37 @@ public void testTextBlockCreation(){
...
+		CtClass<?> allstmt = (CtClass<?>) launcher.getFactory().Type().get("textBlock.TextBlockTestClass");
+		CtMethod<?> m5 =  allstmt.getMethod("m5");
+
+		CtStatement stmt5 = m5.getBody().getStatement(0);
+		assertTrue(stmt5.getValueByRole(CtRole.ASSIGNMENT) instanceof CtTextBlock);
+
+		// test text block value
+		CtTextBlock l1 = (CtTextBlock) stmt5.getValueByRole(CtRole.ASSIGNMENT);
+		assertEquals("no-break space: \\00a0\n" +
+						"newline:        \\n\n" +
```
Comment (algomaster99) [inline src/test/java/spoon/test/textBlocks/TextBlockTest.java:139]: Using `replace("\\", "\\\\")` would only escape the backslashes and not `\n` because the latter is treated as a single character and not a combination of `\` + `n`. For example, if you run `replace("\\", "\\\\")` on `\\\n`, it would return `\\\\\n`. Notice that `\n` is not escaped. I think it would be better if we write a generic function to escape all characters or use one which already exists. I have something like this in mind:
```java
public static String escape(String s){
  return s.replace("\\", "\\\\")
          .replace("\t", "\\t")
          .replace("\b", "\\b")
          .replace("\n", "\\n")
          .replace("\r", "\\r")
          .replace("\f", "\\f")
          .replace("\'", "\\'")
          .replace("\"", "\\\"");
}
```

Comment (xzel23) [reply src/test/java/spoon/test/textBlocks/TextBlockTest.java:139]: As long as in the source code it's written as "\n" it works because at that time it's still two characters. It is not supposed to escape the newline at the end of a line in a textblock. The unit test for this passes and the original problem I had with spoon is also solved by this patch, so I am quote sure it works.

Comment (algomaster99) [reply src/test/java/spoon/test/textBlocks/TextBlockTest.java:139]: > As long as in the source code it's written as "\n" it works because at that time it's still two characters.

Okay. So do we just want to escape backslashes when we put the literal inside a text block?

Comment (xzel23) [reply src/test/java/spoon/test/textBlocks/TextBlockTest.java:139]: Yes, "normal" String literals are handled in LiteralHelper.getLiteralToken(), which in turn calls LiteralHelper.getStringLiteral(). But if we use that one, all newlines, tabs etc. are replaced by their respective escape sequences and all textblocks would be printed on a single line.

Comment (algomaster99) [reply src/test/java/spoon/test/textBlocks/TextBlockTest.java:139]: Okay. Your patch looks good to me in that case.

**Comment by monperrus** [comment]
Thanks a lot @xzel23 for the patch and @algomaster99 for the review.
