### PR TITLE
review: fix: stackoverflow on AbstractTypingContext

### LINKED ISSUE #1783: StackOverflowError with spring-boot maven project
I am getting a StackOverflowError when trying to target the spring-boot project (1.5.9 version). I am using spoon 6.0.0.
Here is the code snippet:

```
String springBoot= "{local directory}/spring-boot-1.5.9.RELEASE/spring-boot";
MavenLauncher launcher = new MavenLauncher(springBoot, MavenLauncher.SOURCE_TYPE.APP_SOURCE);
		launcher.getEnvironment().setNoClasspath(true);
		CtModel model = launcher.buildModel();
		model.getAllTypes().forEach((type) -> {
			type.getAllMethods().forEach((method) -> {
			//TODO
			});
		});

```
The console output (The message is quite long) 
```

Exception in thread "main" java.lang.StackOverflowError
	at spoon.reflect.visitor.CtBiScannerDefault.visitCtTypeParameterReference(CtBiScannerDefault.java:679)
	at spoon.support.reflect.reference.CtTypeParameterReferenceImpl.accept(CtTypeParameterReferenceImpl.java:65)
	at spoon.reflect.visitor.CtAbstractBiScanner.biScan(CtAbstractBiScanner.java:86)
	at spoon.support.visitor.equals.EqualsVisitor.equals(EqualsVisitor.java:30)
	at spoon.support.reflect.declaration.CtElementImpl.equals(CtElementImpl.java:125)
	at spoon.support.visitor.AbstractTypingContext.adaptTypeParameterReferenceBoundingType(AbstractTypingContext.java:82)
	at spoon.support.visitor.AbstractTypingContext.adaptTypeParameterReference(AbstractTypingContext.java:73)
	at spoon.support.visitor.AbstractTypingContext.adaptType(AbstractTypingContext.java:44)
	at spoon.support.visitor.MethodTypingContext.adaptType(MethodTypingContext.java:47)
	at spoon.support.visitor.AbstractTypingContext.adaptType(AbstractTypingContext.java:63)
	at spoon.support.visitor.MethodTypingContext.adaptType(MethodTypingContext.java:47)
	at spoon.support.visitor.MethodTypingContext.isSameMethodFormalTypeParameter(MethodTypingContext.java:252)
	at spoon.support.visitor.MethodTypingContext.hasSameMethodFormalTypeParameters(MethodTypingContext.java:230)
	at spoon.support.visitor.MethodTypingContext.adaptTypeParameter(MethodTypingContext.java:204)
	at spoon.support.visitor.AbstractTypingContext.adaptTypeParameterReference(AbstractTypingContext.java:75)
	at spoon.support.visitor.AbstractTypingContext.adaptType(AbstractTypingContext.java:44)
	at spoon.support.visitor.MethodTypingContext.adaptType(MethodTypingContext.java:47)
	at spoon.support.visitor.AbstractTypingContext.adaptTypeParameterReferenceBoundingType(AbstractTypingContext.java:82)
	at spoon.support.visitor.AbstractTypingContext.adaptTypeParameterReference(AbstractTypingContext.java:73)
	at spoon.support.visitor.AbstractTypingContext.adaptType(AbstractTypingContext.java:44)
	at spoon.support.visitor.MethodTypingContext.adaptType(MethodTypingContext.java:47)
	at spoon.support.visitor.AbstractTypingContext.adaptType(AbstractTypingContext.java:63)
	at spoon.support.visitor.MethodTypingContext.adaptType(MethodTypingContext.java:47)
	at spoon.support.visitor.MethodTypingContext.isSameMethodFormalTypeParameter(MethodTypingContext.java:252)
	at spoon.support.visitor.MethodTypingContext.hasSameMethodFormalTypeParameters(MethodTypingContext.java:230)
	at spoon.support.visitor.MethodTypingContext.adaptTypeParameter(MethodTypingContext.java:204)
	at spoon.support.visitor.AbstractTypingContext.adaptTypeParameterReference(AbstractTypingContext.java:75)
	at spoon.support.visitor.AbstractTypingContext.adaptType(AbstractTypingContext.java:44)
	at spoon.support.visitor.MethodTypingContext.adaptType(MethodTypingContext.java:47)
	at spoon.support.visitor.AbstractTypingContext.adaptTypeParameterReferenceBoundingType(AbstractTypingContext.java:82)
	at spoon.support.visitor.AbstractTypingContext.adaptTypeParameterReference(AbstractTypingContext.java:73)
	at spoon.support.visitor.AbstractTypingContext.adaptType(AbstractTypingContext.java:44)

```
Thanks,

Best,
Mohamed

### PR DESCRIPTION
**Pull request by surli**
Fix #1783

### CODE REVIEW

**Comment by surli** [comment]
@pvojtechovsky could you review this one?

File: src/test/java/spoon/test/method/MethodTest.java [hunk 1]
```diff
@@ -85,4 +86,18 @@ public void testGetAllMethods() throws Exception {
...
+	public void testGetAllMethodsAdaptingType() throws Exception {
+		// contract: AbstractTypingContext should not enter in recursive calls when resolving autoreferenced bounding type
+		// such as T extends Comparable<? super T>
+		Launcher l = new Launcher();
+		l.getEnvironment().setNoClasspath(true);
+		l.addInputResource("src/test/resources/noclasspath/spring/PropertyComparator.java");
+		l.buildModel();
+
+		CtType<?> propertyComparator = l.getModel().getElements(new NamedElementFilter<CtType>(CtType.class, "PropertyComparator")).get(0);
+		CtMethod method = propertyComparator.getMethodsByName("compare").get(0);
```
Comment (pvojtechovsky) [inline src/test/java/spoon/test/method/MethodTest.java]: Which call failed on StackOverflowError? 
A) getMethodsByName
B) getSignature

File: src/test/resources/noclasspath/spring/PropertyComparator.java [hunk 2]
```diff
@@ -0,0 +1,156 @@
+/*
```
Comment (pvojtechovsky) [inline src/test/resources/noclasspath/spring/PropertyComparator.java]: Could you delete as much as possible from this file, so there remains only the code needed to reproduce error?
I do not see there what code caused problem. Or is some combination of all TypeMembers??

File: src/main/java/spoon/support/visitor/MethodTypingContext.java [hunk 3]
```diff
@@ -249,6 +250,27 @@ private boolean isSameMethodFormalTypeParameter(CtTypeParameter scopeParam, CtTy
...
+			CtTypeReference scopeBoundATArg = scopeBound.getActualTypeArguments().get(i);
+			CtTypeReference superBoundATArg = superBound.getActualTypeArguments().get(i);
+
+			if (scopeBoundATArg instanceof CtWildcardReference && superBoundATArg instanceof CtWildcardReference) {
+				CtWildcardReference scopeBoundWildcard = (CtWildcardReference) scopeBoundATArg;
+
+				// we are in a case where we compare Thing<?> with Thing<? super X>
+				// here we choose to not care about X to avoid recursive calls, for example in the case of:
+				// T extends Comparable<? super T>
+				if (scopeBoundWildcard.getBoundingType().equals(scopeMethod.getFactory().Type().getDefaultBoundingType())) {
```
Comment (pvojtechovsky) [inline src/main/java/spoon/support/visitor/MethodTypingContext.java]: May this happen too?
`T extends Comparable<? super List<? extends T>>`
I guess it will end wit stackoverflow too.

Anyway your solution is good fast fix. My example is quite wild and it will need some time until somebody come to such problem again.

**Comment by pvojtechovsky** [comment]
It seems to be OK for me. I will merge it tomorrow after your feedback - whether you want to improve it or keep it as it is.

File: src/test/java/spoon/test/method/MethodTest.java (hunk 1 above)
Comment (surli) [reply src/test/java/spoon/test/method/MethodTest.java]: getMethodsByName

**Comment by surli** [comment]
@pvojtechovsky for me it's ready now.

File: src/test/java/spoon/test/method/MethodTest.java (hunk 1 above)
Comment (pvojtechovsky) [reply src/test/java/spoon/test/method/MethodTest.java]: So why did you removed this method call from the test??

Comment (surli) [reply src/test/java/spoon/test/method/MethodTest.java]: :D sorry I answer yesterday evening and actually I was wrong: it's getAllMethods which led to the bug. My test wasn't failing after all yesterday.

**Comment by pvojtechovsky** [comment]
Thank You Simon ;-)
