### PR TITLE
fix: close the output stream in SourceOptions

### LINKED ISSUE #3083: Code of SourceOptions#sources isn't closing IO streams
/spoon-core/src/main/java/spoon/compiler/builder/SourceOptions.java
```java
	public T sources(List<SpoonFile> sources) {
		if (sources == null || sources.isEmpty()) {
			args.add(".");
			return myself;
		}
		for (SpoonFile source : sources) {
			if (source.isActualFile()) {
				args.add(source.toString());
			} else {
				try {
					File file = File.createTempFile(source.getName(), ".java");
					file.deleteOnExit();
//----------------> the streams created on next line are never closed
					IOUtils.copy(source.getContent(), new FileOutputStream(file));
					args.add(file.toString());
				} catch (IOException e) {
					throw new RuntimeException(e.getMessage(), e);
				}
			}
		}
		return myself;
	}
```

### PR DESCRIPTION
**Pull request by tdurieux**
close #3083

### CODE REVIEW

**Comment by nharrand** [comment]
Thanks!

File: src/main/java/spoon/compiler/builder/SourceOptions.java [hunk 1]
```diff
@@ -50,7 +50,9 @@ public T sources(List<SpoonFile> sources) {
 				try {
 					File file = File.createTempFile(source.getName(), ".java");
 					file.deleteOnExit();
-					IOUtils.copy(source.getContent(), new FileOutputStream(file));
+					try (FileOutputStream fileOutputStream = new FileOutputStream(file)) {
+						IOUtils.copy(source.getContent(), fileOutputStream);
```
Comment (pvojtechovsky) [inline src/main/java/spoon/compiler/builder/SourceOptions.java]: source.getContent() has to be closed too, shouldn't?

**Comment by pvojtechovsky** [comment]
@tdurieux source.getContent() has to be closed too, shouldn't?
