### PR TITLE
fix: Make SortedList#add return value adhere to List contract

### LINKED ISSUE #6034: [Bug]: spoon.support.util.SortedList.addAll(...) return value is not JLS compliant
### Describe the bug

According to Java JLS/API docs we see that:
https://docs.oracle.com/javase/8/docs/api/?java/util/Collections.html
addAll(...) Returns:
    true if the collection changed as a result of the call

However in spoon.support.util.SortedList.addAll(...) calling addAll(...) on an empty collection returns true, even though no actual change was made in the collections and secondly, if some element fails to be added, despite some of them are added will return false, when at least one object was inserted in the collection, and thus the collection was modified.

It should also be noted that LinkedList which SortedList extends always inserts all elements and returns true. It only returns false if no element could be added and that if some problem occurs at the middle of an insertion of multiple objects, an exception will be thrown.

We propose the following patch:
```
--- a/src/main/java/spoon/support/util/SortedList.java	2024-10-23 02:02:48.000000000 +0100
+++ b/src/main/java/spoon/support/util/SortedList.java	2024-10-23 17:25:47.531343136 +0100
@@ -42,9 +42,9 @@
 
 	@Override
 	public boolean addAll(Collection<? extends E> c) {
-		boolean ret = true;
+		boolean ret = false;
 		for (E e : c) {
-			ret &= add(e);
+			ret |= add(e);
 		}
 		return ret;
 	}
```

### Source code you are trying to analyze/transform

_No response_

### Source code for your Spoon processing

_No response_

### Actual output

_No response_

### Expected output

_No response_

### Spoon Version

latest from master

### JVM Version

Java 17, but not relevant for this problem

### What operating system are you using?

NixOS Linux, but again not relevant for this issue

### PR DESCRIPTION
**Pull request by CoreRasurae**
- Fixes #6034 
- SortedList.addAll(...) should return a boolean value indicating if the Collection was modified is any way as a result of the call
- Previously addAll(...) would return false if only partial changes occurred and would only return true if all elements had been inserted, or if adding an empty list which in not in accordance to the Java JLS/API as documented in https://docs.oracle.com/javase/8/docs/api/?java/util/Collections.html.

### CODE REVIEW

File: src/main/java/spoon/support/util/SortedList.java [hunk 1]
```diff
@@ -42,9 +42,9 @@ public void add(int index, E element) {
 
 	@Override
 	public boolean addAll(Collection<? extends E> c) {
-		boolean ret = true;
+		boolean ret = false;
 		for (E e : c) {
-			ret &= add(e);
+			ret |= add(e);
```
Comment (SirYwell) [inline src/main/java/spoon/support/util/SortedList.java:47]: As we'll always return `true` this way (because `add` always returns true), we can probably also just return `!c.isEmpty()` (assuming `c` doesn't get modified in between) or just do `ret = true`, similar to the default implementation in `AbstractList`. What do you think? (Seems like the Qodana inspection is a bit aggressive here...)

**Review by SirYwell — COMMENTED** [review]
One minor thing, other than that, please make sure your PR title follows our guidelines (<https://github.com/INRIA/spoon/blob/master/CONTRIBUTING.md#guidelines-for-pull-requests>). Thanks!

File: src/main/java/spoon/support/util/SortedList.java (hunk 1 above)
Comment (CoreRasurae) [reply src/main/java/spoon/support/util/SortedList.java]: Qodana is right i didn't notice it was using bit-wise operations instead of logical operations i have fixed that now

Comment (CoreRasurae) [reply src/main/java/spoon/support/util/SortedList.java]: I hope the PR title is okay now

Comment (CoreRasurae) [reply src/main/java/spoon/support/util/SortedList.java]: i hope that the title is okay now... trying to follow the procedures that indicate that fic and the number of the issue needs to be present too

Comment (CoreRasurae) [reply src/main/java/spoon/support/util/SortedList.java]: Ping?

Comment (SirYwell) [reply src/main/java/spoon/support/util/SortedList.java]: Please use one of my suggested variants or your initial version instead of the `||`. The title is fine now.

Comment (CoreRasurae) [reply src/main/java/spoon/support/util/SortedList.java:47]: Okay, i've reverted the change to use bit-wise logic again.

**Review by SirYwell — APPROVED** [review]

**Comment by CoreRasurae** [comment]
I am unable to merge... The base branch restricts merging to authorized users.

**Comment by SirYwell** [comment]
> @CoreRasurae Qodana still fails. Could you take a look? @SirYwell would merge afterwards.

The Qodana problem is basically a false positive. A short-circuit operation isn't intuitive there at all imho.
