### PR TITLE
Fix FQN regression in FQN mode

### LINKED ISSUE #1041: Improvement: setAutoimport and DefaultJavaPrettyPrinter
With the new implementation of ImportScanner, MinimalImportScanner, we must change the way/the moment when DefaultJavaPrettyPrinter create the instance of ImportScanner, because if we call setAutoImport after the instance creation, it will never change in DefaultJavaPrettyPrinter resulting in bad behaviour.

### PR DESCRIPTION
**Pull request by surli**
The previously implemented `MinimalImportScanner` was only comparing FQN against list of previously explored variables, which means all variables were considered even those which were not on the scope of the current variable. It fixes issue #1045.
The proposed implementation now only check the current scope to search name collisions.
Moreover, now the ImportScanner is recreated in DefaultJavaPrettyPrinter when `calculate` method is called: it avoids the scanner to test collision names against another class variable names, but it should also fix #1041 (to be tested).

### CODE REVIEW

File: src/main/java/spoon/reflect/visitor/ImportScannerImpl.java [hunk 1]
```diff
@@ -64,6 +64,20 @@
 	protected CtTypeReference<?> targetType;
 	private Map<String, Boolean> namesPresentInJavaLang = new HashMap<>();
 
+	/**
+	 * Determine if the ImportScanner should work in a FQN mode or in auto import mode.
+	 */
+	private boolean fqnMode;
```
Comment (surli) [inline src/main/java/spoon/reflect/visitor/ImportScannerImpl.java]: handle with polymorphism
