### PR TITLE
fix: printing of generic records (issue #4281)

### LINKED ISSUE #4281: [Bug] generic records output is wrong
**Describe the bug**
Generic record output is wrong, the generic type is printed to the right of the argument list.

**To Reproduce**

Input:
```java
public record A<T>(int a, int b) {}
```

Processing with Spoon:
```java
        String code = "public record A<T>(int a, int b) {}";

        Launcher launcher = new Launcher();
        launcher.addInputResource(new VirtualFile(code));
        launcher.getEnvironment().setComplianceLevel(16);
        launcher.getEnvironment().setNoClasspath(true);
        launcher.getEnvironment().setAutoImports(true);

        CtModel model = launcher.buildModel();

        System.out.println(model.getRootPackage().getType("A").toString());
```

Output:
```java
public record A(int a, int b)<T> {}
```

Note that you can also open a pull request reproducing the issue and reference that, instead of writing additional information here.

**Operating system, JDK and Spoon version used**

* OS: MacOS 12.0.1
* JDK: same result with Oracle OpenJDK 17 and GraalVM CE 21.3.0 
* Spoon version: same result with 10.0.0 and 10.0.1-beta-1 (maven central repository)

### PR DESCRIPTION
**Pull request by xzel23**
Fix #4281 

This PR moves the type argument to the correct location when printing generic record declarations. A new unit test is included.

### CODE REVIEW

File: src/test/resources/records/GenericRecord.java [hunk 1]
```diff
@@ -0,0 +1,3 @@
+package records;
+
+public record GenericRecord<T>(T a, T b) {}
```
Comment (algomaster99) [inline src/test/resources/records/GenericRecord.java:3]: I think this line is syntactically incorrect. Instead of `record`, there should be `class`, `interface`, or even `enum`. I tried running the tests after replacing `record` with `class` and it returned the expected string.

**Review by algomaster99 — COMMENTED** [review]
Hi @xzel23 !

Thank you for the pull request. Please look at my comment.

File: src/test/resources/records/GenericRecord.java (hunk 1 above)
Comment (algomaster99) [inline src/test/resources/records/GenericRecord.java:3]: Could you please add this test case under `src/test/resources/records`? It's where we put all the tests related to records.

File: src/test/java/spoon/test/record/CtRecordTest.java [hunk 2]
```diff
@@ -146,6 +146,16 @@ private CtModel createModelFromPath(String code) {
 		return model;
 	}
 
+	@Test
+	void printGenericRecord() {
```
Comment (algomaster99) [inline src/test/java/spoon/test/record/CtRecordTest.java:150]: We try to name new tests we create by describing what is happening in the test. I think a better name would be `testGenericTypeParametersArePrintedBeforeTheFunctionParameters`.

**Review by algomaster99 — APPROVED** [review]
It looks good to me. Thanks, @xzel23 ! I am sorry I gave a misinformed review first.

Anyway, @monperrus @slarse , you can also have a look.

**Comment by xzel23** [comment]
@algomaster99 Yes, I have seen code in Spoon using "record" as a variable name in the test classes. That code will probably break when compiling in Java 14+ where it was introduced as a keyword. The code in the unit test actually is more or less taken from one of my source files that compile perfectly but cannot be handled by spoon.

File: src/test/resources/records/GenericRecord.java (hunk 1 above)
Comment (xzel23) [reply src/test/resources/records/GenericRecord.java:3]: Hm... I think the suggested path is the same as where the file is currently located. But I think I should update the package name.

File: src/test/java/spoon/test/record/CtRecordTest.java (hunk 2 above)
Comment (xzel23) [reply src/test/java/spoon/test/record/CtRecordTest.java:150]: OK, will update the PR

**Comment by algomaster99** [comment]
> That code will probably break when compiling in Java 14+

@xzel23 We don't compile our test resources before using them in tests and probably that's why all the [tests are green when executed in ubuntu/Java 16 environment](https://github.com/INRIA/spoon/runs/4188656082?check_suite_focus=true). Should we consider compiling our test resources, @slarse? We do it in `diffmin`, but I know it will really hard to do that in `spoon` because of the number of resources we have in this project.

> cannot be handled by spoon.

Spoon doesn't compile code before building the model. You can even create a model for syntactically incorrect code. For example,
```java
public class A {
    x;
}
```
The return type of field is missing.

However, we guarantee correct transformations only for syntactically correct code. What you encountered was a bug in the printer (thanks for the fix). In other words, spoon created a valid [model](https://spoon.gforge.inria.fr/mvnsites/spoon-core/apidocs/spoon/reflect/CtModel.html) for your code. It just failed to print it correctly when you called `toString`.

**Comment by xzel23** [comment]
@algomaster99 I just learned that using `record` as a variable name is indeed legal even in Java 14+ where it is a keyword. The JLS defines it as a [contextual keyword](https://docs.oracle.com/javase/specs/jls/se17/html/jls-3.html#jls-3.9).

**Comment by algomaster99** [comment]
> variable name is indeed legal even in Java 14+ where it is a keyword.

Oh, nice. Our test resources are free of at least one possible error :)

Thanks for renaming the test. Could you also shift the resource to the suggested directory?

**Comment by xzel23** [comment]
@algomaster99 I would do it, but I'm afraid I can't ;-)

Please compare the paths. First one is the current resource path, second one the suggestzed directory:

`src/test/resources/records/GenericRecord.java`
`src/test/resources/records`

I don't see any difference. Where should I move the file to?

**Comment by algomaster99** [comment]
Oh, right. I mistook the path because of diffs in multiple file. 😅 I think we are good to go. Let maintainers approve your PR for workflow and then we will review further, if needed.

File: src/test/java/spoon/test/record/CtRecordTest.java [hunk 3]
```diff
@@ -146,6 +146,16 @@ private CtModel createModelFromPath(String code) {
 		return model;
 	}
 
+	@Test
+	void testGenericTypeParametersArePrintedBeforeTheFunctionParameters() {
+		// a record with generic type arguments should be printed correctly
```
Comment (MartinWitt) [inline src/test/java/spoon/test/record/CtRecordTest.java:151]: Could you add a `// contract:  ... a record with generic type arguments should be printed correctly`?

**Review by MartinWitt — APPROVED** [review]

**Comment by slarse** [comment]
> We don't compile our test resources before using them in tests 

This is by design, a lot of the test resources can't compile as they are missing dependencies. It would however be neat to check the syntax. There's already something along the lines of a syntax check implemented in `TreeBuilderCompiler.ignoreSyntaxErrors`, could probably start from there.

Approved the workflow, getting back to this later.

File: src/test/java/spoon/test/record/CtRecordTest.java (hunk 3 above)
Comment (xzel23) [reply src/test/java/spoon/test/record/CtRecordTest.java]: done

**Comment by slarse** [comment]
@MartinWitt you approved with a comment, are you happy with the PR? if so I merge.

**Comment by MartinWitt** [comment]
yes you can merge.

**Comment by slarse** [comment]
@MartinWitt okidoki

Thanks @xzel23 for the fix!
