### PR TITLE
fix: Adds all references via TypeReferenceScanner.

### LINKED ISSUE #174: Bug in getReferencedTypes
it seems that AudioFormat.Encoding dependency is not detected by getReferencedTypes

```
import javax.sound.sampled.AudioFormat;
import javax.sound.sampled.AudioFormat.Encoding;
import java.util.HashMap;

public class Bar {
    public AudioFormat doSomething() {
        return new AudioFormat(Encoding.ALAW, (float)1.0, 8, 2, 1, (float)1.0, true, new HashMap<String, Object>());
    }
}
```

### PR DESCRIPTION
**Pull request by GerardPaligot**
Before, in the TypeReferenceScanner, if the enclosing reference
of the current reference is already in the set of references,
we didn't add it in the set. Now, we add all in set and the Set
class remove all duplicate items.

Closes #174

### CODE REVIEW

File: src/test/java/spoon/test/api/NoClasspathTest.java [hunk 1]
```diff
@@ -108,5 +113,32 @@ public void testBug20141021() {
...
+		Launcher spoon = new Launcher();
+		final Factory factory = spoon.getFactory();
+		factory.getEnvironment().setAutoImports(false);
+		spoon.addInputResource("./src/test/java/spoon/test/api/testclasses/");
+		spoon.run();
+
+		CtTypeReference expectedType = factory.Type().createReference(javax.sound.sampled.AudioFormat.Encoding.class);
+		CtClass<?> clazz = factory.Class().get(Bar.class);
+
+		try {
```
Comment (monperrus) [inline src/test/java/spoon/test/api/NoClasspathTest.java]: remove try block

File: src/test/java/spoon/test/api/NoClasspathTest.java [hunk 2]
```diff
@@ -108,5 +113,32 @@ public void testBug20141021() {
...
+			CtMethod<?> method = clazz.getMethodsByName("doSomething").get(0);
+			CtReturn ctReturn = method.getElements(new TypeFilter<CtReturn>(CtReturn.class)).get(0);
+
+			Set<CtTypeReference> references = new HashSet<CtTypeReference>();
+
+			for (CtTypeReference<?> type : ctReturn.getReferencedTypes()) {
+				references.add(type);
+			}
+
+			assertEquals(true, references.contains(expectedType));
```
Comment (monperrus) [inline src/test/java/spoon/test/api/NoClasspathTest.java]: why not simply ctReturn.getReferencedTypes().contains(...)?
