### PR TITLE
review: fix: ImportBuilder to check visibility when importing starred imports

### LINKED ISSUE #1587: Bug: error with star imports and visibilities of classes
Hi all,

Spoon doesn't check the visibility of classes when build imports, that results in error if Spoon wants to replace the star `*` by an non-public class.

Cheers.

### PR DESCRIPTION
**Pull request by surli**
Fix #1587

### CODE REVIEW

File: src/main/java/spoon/support/compiler/jdt/JDTImportBuilder.java [hunk 1]
```diff
@@ -78,7 +78,9 @@ public void build() {
 
 					if (ctPackage != null) {
 						for (CtType type : ctPackage.getTypes()) {
-							this.imports.add(type.getReference());
+							if (type.getVisibility() == ModifierKind.PUBLIC) {
```
Comment (monperrus) [inline src/main/java/spoon/support/compiler/jdt/JDTImportBuilder.java]: should also work with package-visible if both classes are in the same package?

Comment (surli) [reply src/main/java/spoon/support/compiler/jdt/JDTImportBuilder.java]: Yes, but if both classes are in the same packages, it's useless to import them...
