### PR TITLE
fix(annotation): Supports enum fields with Annotation#annotate() method.

### LINKED ISSUE #750: Enum Value as annotation type value not possible
I am trying to annotate a field via the annotation factory, and would like to set the value of an annotation element to an enum value, e.g.

`annoFactory.annotate(field, BoundNumber.class, "byteOrder", ByteOrder.LittleEndian);`

where ByteOrder.LittleEndian is the enum value. Running the annoation processor, I get the error message

> "Please, submit a valid value."

In CtAnnotationImpl.java, starting at line 88, the annotation values passed in are converted to CtExpression values, but I can not find any clause that would match en enum value. What is the proper way to convert an enum value as shown above to the according CtExpression instance?

### PR DESCRIPTION
**Pull request by GerardPaligot**
Closes #750

### CODE REVIEW

File: src/test/java/spoon/test/annotation/AnnotationValuesTest.java [hunk 1]
```diff
@@ -102,6 +105,18 @@ public void testAnnotationFactory() throws Exception {
...
 
+	@Test
+	public void testAnnotateWithEnum() throws Exception {
+		final Factory factory = createFactory();
+		final CtClass<Object> target = factory.Class().create("org.example.Tacos");
+		final CtField<String> field = factory.Field().create(target, new HashSet<>(), factory.Type().STRING, "field");
+		target.addField(field);
+
+		final CtAnnotation<BoundNumber> byteOrder = factory.Annotation().annotate(field, BoundNumber.class, "byteOrder", BoundNumber.ByteOrder.LittleEndian);
+		on(field).giveMeAnnotation(BoundNumber.class);
```
Comment (monperrus) [inline src/test/java/spoon/test/annotation/AnnotationValuesTest.java]: assertEquals with byteOrder

File: src/test/java/spoon/test/annotation/AnnotationValuesTest.java [hunk 2]
```diff
@@ -102,6 +105,18 @@ public void testAnnotationFactory() throws Exception {
...
+		on(byteOrder).giveMeAnnotationValue("byteOrder");
```
Comment (monperrus) [inline src/test/java/spoon/test/annotation/AnnotationValuesTest.java]: add assert on result

**Comment by GerardPaligot** [comment]
@monperrus PR ready.
