### PR TITLE
fix(shadow): fix the creation of a partial shadow class

### LINKED ISSUE #2038: Shadow and partial classpath
I think there is a major bug in the Shadow.

You have:
- A in the source
- B referenced in A and is in the classpath
- C referenced in B but is not in the classpath

The creation of the shadow of B will fail because when we will try to create the shadow of C a SpoonClassNotFound will be thrown and the creation of the shadow of B will stop.

### PR DESCRIPTION
**Pull request by tdurieux**
It is a little bit dirty, do you have better idea how to do it?

Fix #2038

### CODE REVIEW

File: src/main/java/spoon/support/visitor/java/JavaReflectionVisitorImpl.java [hunk 1]
```diff
@@ -46,38 +45,70 @@ public void visitPackage(Package aPackage) {
...
 			clazz.getPackage();
 		}
-		for (TypeVariable<Class<T>> generic : clazz.getTypeParameters()) {
-			visitTypeParameter(generic);
+		try {
+			for (TypeVariable<Class<T>> generic : clazz.getTypeParameters()) {
+				visitTypeParameter(generic);
+			}
+		} catch (Throwable ignore) {
+			// partial classpath
```
Comment (pvojtechovsky) [inline src/main/java/spoon/support/visitor/java/JavaReflectionVisitorImpl.java]: can we catch more exact exception? Such error handling may cause big problems during future debugging.

File: src/main/java/spoon/support/visitor/java/JavaReflectionVisitorImpl.java [hunk 2]
```diff
@@ -46,38 +45,70 @@ public void visitPackage(Package aPackage) {
...
+				visitTypeReference(CtRole.SUPER_TYPE, clazz.getGenericSuperclass());
+			}
+		} catch (Throwable ignore) {
+			// partial classpath
 		}
-		for (Type anInterface : clazz.getGenericInterfaces()) {
-			visitTypeReference(CtRole.INTERFACE, anInterface);
+		try {
+			for (Type anInterface : clazz.getGenericInterfaces()) {
+				visitTypeReference(CtRole.INTERFACE, anInterface);
```
Comment (pvojtechovsky) [inline src/main/java/spoon/support/visitor/java/JavaReflectionVisitorImpl.java]: I suggest to try/catch this line only. So some interfaces are correctly created and some are ignored. Actually it process all interfaces until first which is not on classpath.

Do the same in all cycles of this method, please.

File: src/main/java/spoon/support/visitor/java/JavaReflectionVisitorImpl.java [hunk 3]
```diff
@@ -131,46 +187,70 @@ public void visitPackage(Package aPackage) {
...
 		}
-		for (Constructor<?> constructor : clazz.getDeclaredConstructors()) {
-			if (Modifier.isPrivate(constructor.getModifiers())) {
-				Class<?>[] paramTypes = constructor.getParameterTypes();
-				if (paramTypes.length == 2 && paramTypes[0] == String.class && paramTypes[1] == int.class) {
-					//ignore implicit enum constructor
+		try {
+			for (Annotation annotation : clazz.getDeclaredAnnotations()) {
+				visitAnnotation(annotation);
+			}
```
Comment (pvojtechovsky) [inline src/main/java/spoon/support/visitor/java/JavaReflectionVisitorImpl.java]: This for cycle seems to be copy past here by mistake. It is already above. Please fix it

File: src/main/java/spoon/support/visitor/java/JavaReflectionVisitorImpl.java (hunk 2 above)
Comment (tdurieux) [reply src/main/java/spoon/support/visitor/java/JavaReflectionVisitorImpl.java]: I cannot the Error is thrown by clazz.getGenericInterfaces()

File: src/main/java/spoon/support/visitor/java/JavaReflectionVisitorImpl.java (hunk 3 above)
Comment (tdurieux) [reply src/main/java/spoon/support/visitor/java/JavaReflectionVisitorImpl.java]: I don't understand it is the only loop on clazz.getDeclaredAnnotations() for visitEnum(Class<T> clazz).
Did I miss something?

File: src/main/java/spoon/support/visitor/java/JavaReflectionVisitorImpl.java (hunk 2 above)
Comment (tdurieux) [reply src/main/java/spoon/support/visitor/java/JavaReflectionVisitorImpl.java]: and I did not succeed to find a way to get a partial list :/

File: src/main/java/spoon/support/visitor/java/JavaReflectionVisitorImpl.java (hunk 3 above)
Comment (pvojtechovsky) [reply src/main/java/spoon/support/visitor/java/JavaReflectionVisitorImpl.java]: See line 142-144 in this file

File: src/main/java/spoon/support/visitor/java/JavaReflectionVisitorImpl.java (hunk 2 above)
Comment (pvojtechovsky) [reply src/main/java/spoon/support/visitor/java/JavaReflectionVisitorImpl.java]: So then try/catch only clazz.getGenericSuperclass(). So the exceptions thrown in visitTypeReference are not catched

File: src/main/java/spoon/support/visitor/java/JavaReflectionVisitorImpl.java (hunk 3 above)
Comment (tdurieux) [reply src/main/java/spoon/support/visitor/java/JavaReflectionVisitorImpl.java]: It is not the same method

Comment (pvojtechovsky) [reply src/main/java/spoon/support/visitor/java/JavaReflectionVisitorImpl.java]: I see. First one processes Interface and second one processes Enum. You are right. It is correct. Thanks for explanation.

File: src/main/java/spoon/support/visitor/java/JavaReflectionVisitorImpl.java (hunk 2 above)
Comment (tdurieux) [reply src/main/java/spoon/support/visitor/java/JavaReflectionVisitorImpl.java]: I don't have the motivation to do it, right now. 
There is probably 50 invocations to protect in this class.

Comment (pvojtechovsky) [reply src/main/java/spoon/support/visitor/java/JavaReflectionVisitorImpl.java]: it can be written in nice way using lambda:
`for (Type anInterface : ignoreMissingClass(()->clazz.getGenericInterfaces()))`
where ignoreMissingClass will return empty collection in case of exception

Comment (tdurieux) [reply src/main/java/spoon/support/visitor/java/JavaReflectionVisitorImpl.java]: clazz.getGenericInterfaces() returns an array not a collection.
I don't see a way to do it nicely :/

Comment (tdurieux) [reply src/main/java/spoon/support/visitor/java/JavaReflectionVisitorImpl.java]: but the problem is to create EMPTY_ARR, because EMPTY_ARR has to be different for each T

**Comment by monperrus** [comment]
LGTM.
