### PR TITLE
fix: Circular references with generic types.

### LINKED ISSUE #368: unable to spoon RxJava
```
Caused by: java.lang.NullPointerException
	at spoon.support.compiler.jdt.JDTTreeBuilder.createType(JDTTreeBuilder.java:946)
	at spoon.support.compiler.jdt.JDTTreeBuilder.visit(JDTTreeBuilder.java:2972)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.traverse(TypeDeclaration.java:1374)
	at spoon.support.compiler.jdt.JDTTreeBuilder.visit(JDTTreeBuilder.java:2511)
	at org.eclipse.jdt.internal.compiler.ast.QualifiedAllocationExpression.traverse(QualifiedAllocationExpression.java:604)
	at spoon.support.compiler.jdt.JDTTreeBuilder.visit(JDTTreeBuilder.java:2315)
	at org.eclipse.jdt.internal.compiler.ast.MessageSend.traverse(MessageSend.java:1031)
	at org.eclipse.jdt.internal.compiler.ast.Block.traverse(Block.java:139)
	at spoon.support.compiler.jdt.JDTTreeBuilder.visit(JDTTreeBuilder.java:1602)
	at org.eclipse.jdt.internal.compiler.ast.LambdaExpression.traverse(LambdaExpression.java:678)
	at spoon.support.compiler.jdt.JDTTreeBuilder.visit(JDTTreeBuilder.java:2315)
	at org.eclipse.jdt.internal.compiler.ast.MessageSend.traverse(MessageSend.java:1031)
	at spoon.support.compiler.jdt.JDTTreeBuilder.visit(JDTTreeBuilder.java:2219)
	at org.eclipse.jdt.internal.compiler.ast.LocalDeclaration.traverse(LocalDeclaration.java:301)
	at spoon.support.compiler.jdt.JDTTreeBuilder.visit(JDTTreeBuilder.java:2396)
	at org.eclipse.jdt.internal.compiler.ast.MethodDeclaration.traverse(MethodDeclaration.java:327)
	at spoon.support.compiler.jdt.JDTTreeBuilder.visit(JDTTreeBuilder.java:3053)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.traverse(TypeDeclaration.java:1319)
	at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.traverse(CompilationUnitDeclaration.java:748)
	at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.traverse(CompilationUnitDeclaration.java:709)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildSources(JDTBasedSpoonCompiler.java:227)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:480)
	at spoon.Launcher.buildModel(Launcher.java:664)
	at spoon.Launcher.run(Launcher.java:616)
	at spoon.SpoonAPI$run$1.call(Unknown Source)
```
As far as I can tell the logging is not granular enough to narrow down the scope of the problem. I'm trying to analyze the [RxJava 2.x sources][1] (note the `2.x` branch). Unfortunately there's quite a lot of classes and they are interdependent so I've been unable to find the cause.

I was forced onto 4.4.0-SNAPSHOT as when attempting this with 4.3.0 another error occurred:
```
Caused by: java.lang.RuntimeException: Unknown TypeBinding: class org.eclipse.jdt.internal.compiler.lookup.IntersectionCastTypeBinding capture#776-of ? super T & capture#778-of ? super T
	at spoon.support.compiler.jdt.JDTTreeBuilder$ReferenceBuilder.getTypeReference(JDTTreeBuilder.java:617)
	at spoon.support.compiler.jdt.JDTTreeBuilder$ReferenceBuilder.getTypeReference(JDTTreeBuilder.java:461)
	at spoon.support.compiler.jdt.JDTTreeBuilder.buildCommonPartForCtNewClassAndCtConstructorCall(JDTTreeBuilder.java:1611)
	at spoon.support.compiler.jdt.JDTTreeBuilder.visit(JDTTreeBuilder.java:1592)
	at org.eclipse.jdt.internal.compiler.ast.AllocationExpression.traverse(AllocationExpression.java:657)
	at spoon.support.compiler.jdt.JDTTreeBuilder.visit(JDTTreeBuilder.java:2279)
	at org.eclipse.jdt.internal.compiler.ast.MessageSend.traverse(MessageSend.java:1008)
	at org.eclipse.jdt.internal.compiler.ast.ReturnStatement.traverse(ReturnStatement.java:373)
	at spoon.support.compiler.jdt.JDTTreeBuilder.visit(JDTTreeBuilder.java:2360)
	at org.eclipse.jdt.internal.compiler.ast.MethodDeclaration.traverse(MethodDeclaration.java:317)
	at spoon.support.compiler.jdt.JDTTreeBuilder.visit(JDTTreeBuilder.java:3024)
	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.traverse(TypeDeclaration.java:1338)
	at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.traverse(CompilationUnitDeclaration.java:748)
	at org.eclipse.jdt.internal.compiler.ast.CompilationUnitDeclaration.traverse(CompilationUnitDeclaration.java:709)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildSources(JDTBasedSpoonCompiler.java:247)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:500)
	at spoon.Launcher.buildModel(Launcher.java:748)
	at spoon.Launcher.run(Launcher.java:700)
	at spoon.SpoonAPI$run$1.call(Unknown Source)
```
Perhaps that provides some insight into what the cause might be.

 [1]: https://github.com/ReactiveX/RxJava/tree/2.x

### PR DESCRIPTION
**Pull request by GerardPaligot**
When you have an invocation to a method with this
kind of reference : <T extends Comparable<? extends T>>,
you got a circular reference and a StackOverflowException.
With this PR, we add a cache which detects circular references
in JDTTreeBuilder and uses this information in
CtScanner and DefaultJavaPrettyPrinter.

Closes #368

### CODE REVIEW

**Comment by monperrus** [comment]
Looks much better, then the next step is to remove the change ine the factory interface.

also CtCircularTypeReference should not be the main metamodel (in package reflect).

we need a way to dissociate internal machinery marker interfaces from real ones of the metamodel. if we find a good solution, we can then clean reflect (such as for instance ImplicitTypeReference)

**Comment by GerardPaligot** [comment]
`CtCircularTypeReference` isn't an internal node, it is exposed in the final AST.

File: src/main/java/spoon/reflect/factory/CoreFactory.java [hunk 1]
```diff
@@ -405,6 +406,11 @@ SourcePosition createSourcePosition(
 	<T> CtTypeReference<T> createTypeReference();
 
 	/**
+	 * Creates a circular type reference.
+	 */
+	<T> CtCircularTypeReference createCircularTypeReference();
```
Comment (GerardPaligot) [inline src/main/java/spoon/reflect/factory/CoreFactory.java]: Moves to factory.Internal()

File: src/main/java/spoon/reflect/reference/CtCircularTypeReference.java [hunk 2]
```diff
@@ -0,0 +1,4 @@
+package spoon.reflect.reference;
+
+public interface CtCircularTypeReference extends CtTypeParameterReference {
```
Comment (GerardPaligot) [inline src/main/java/spoon/reflect/reference/CtCircularTypeReference.java]: Javadoc

File: src/main/java/spoon/reflect/reference/CtCircularTypeReference.java [hunk 3]
```diff
@@ -0,0 +1,4 @@
+package spoon.reflect.reference;
```
Comment (GerardPaligot) [inline src/main/java/spoon/reflect/reference/CtCircularTypeReference.java]: Moves to `spoon.internal`
